### ISSUE TITLE
Provide auto-complete for custom commands 

### ISSUE THREAD

**Issue by BenjaminNavarro** [James-Yu/Atom-LaTeX#103]
I would be great to have user-defined commands (e.g. `\newcommand{\Bold}[1]{\textbf{#1}}`) showing up in the completions list.

In my case I have a `latex_commands.tex` file, included in the root document (using `\include{latex_commands}`), where I keep all my custom commands. TexStudio handles with and its the only thing that bothers me when using Atom-Latex.

Is it possible to provide such a feature?

**Comment by ashthespy** [comment]
Currently custom commands are read only from active editors, and not all files from the project. 
As a workaround, try opening `latex_commands.tex` once!

**Comment by BenjaminNavarro** [comment]
Well, the file was already open in one tab but the commands inside doesn't show up...
For info I have Atom-Latex 0.8.1 installed with Atom 1.18.0

**Comment by ashthespy** [comment]
Nevermind my previous comment - All `include{}` files are also parsed for commands. Let me look a bit deeper.

**Comment by BenjaminNavarro** [comment]
I found a solution, I had the "Symbol" provider selected in autocomplete-plus settings, changing it to "Fuzzy" makes the completion work as you mentioned

**Comment by ashthespy** [comment]
Nice, didn't know of that one! :-)

**Comment by BenjaminNavarro** [comment]
But it still doesn't seem to work with included but not open files

**Comment by ashthespy** [comment]
Yes, as the included files are parsed for commands of the format `\command{}{}{}` currently.
So `\newcommand{\Bold}[1]{\textbf{#1}}` leads to suggestions of `\newcommand{ }` and `\textbf{ }`

I will have a look at recognising `\newcommand{}` and `\def` but it's not going to be that quick ;-)

**Comment by stakaz** [comment]
Hello, so this is still true: autocompletion for custom commands works only after using the command once?
Would it be possible to make an option to always include any custom command to the auto-completion list? I have a large commands.tex file which I use in different projects and I do not remember any single  command exactly. So in a new project I have to manually look up any command which was not used before. Even better would be a possibility to pass a package which has some \newcommand \renewcommand entries and to automatically ad all of them to the completion. By this you will add a very handy feature of including "custom" commands which you need only in some projects (like beamer...).

**Comment by ashthespy** [comment]
@stakaz All depended `tex` files are parsed for commands - so your `commands.tex` file should also be parsed (when it finds a `
\incldue{commands.tex}`) and should show up in the suggestions. Or are you experiencing different behaviour? 

About the package commands - that indeed would be lovely - but I can't off the top of my hat think of an elegant solution to do it. Unless each package exports a list of commands/documents it in a parse able fashion?

**Comment by stakaz** [comment]
Well, I have the following sturcture:
```
root.tex 
    \import{preamble_report}
preamble_report.tex
    \import{preamble_global}
preamble_global.tex
     \import{commands}
```
Used commands from commands.tex ar shown as suggestions but not all.

**Comment by ashthespy** [comment]
Could you share a sample of the commands that are proving to be problematic?

**Comment by stakaz** [comment]
Essentially every unused command. Example would be:
```
\newcommand{\pardiff}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\id}{\mathds{1}}
```

I have also tried to use `\include{commands}` directly in the `root.tex` file but no luck.

**Comment by stakaz** [comment]
I have the solution: \include{commands.tex} needs to have the file in the same root folder. Now everything is working as expected.

**Comment by stakaz** [comment]
Oh now, I have another thing: commands without arguments expend to `\command{}` while it would be enough to have `\command`.

**Comment by ashthespy** [comment]
Oh that is interesting about the path issue - this is a bug not a feature ;-)
I will have a look.

Noted about the `\command` will fix that as well :-)

**Comment by stakaz** [comment]
The thing with the path of include is that it can only point to the root directory or child directory but not to another place. Otherwise latex cannot create an .aux file. So the question is: should also `\import` work for adding commands to autocompletion or not?
