### ISSUE TITLE
Unable to call xelatex?

### ISSUE THREAD

**Issue by GitatHub** [James-Yu/Atom-LaTeX#105]
Failed to compile files that must use xelatex with latexmk in Windows 10.
I did not see xelatex command calling support in the description page of the package.

**Comment by ashthespy** [comment]
Just edit the `latexmkmk execution parameters` in the settings?
The current default is: `-synctex=1 -interaction=nonstopmode -file-line-error -pdf`
For XeLaTeX, you can with latexmk (since v 4.3.1) you can just add a `-xelatex` flag at the  end.
