### ISSUE TITLE
Watchers does not work with NFS mounted directory

### ISSUE THREAD

**Issue by fkjogu** [James-Yu/Atom-LaTeX#108]
My `home` is mounted via NFS. For projects in `home` autocompletion of citations and references does not work. I only get a status message
```
Watching project <projectname> for changes
```
and nothing else happens. Also when trying to invoke autocompletion manually.

However, copying the same project to the local hard drive it works flawlessly. Any ideas?

**Comment by ashthespy** [comment]
Hi there,
The watcher module used requires polling for network mounts, which could increases CPU usage, and is hence disabled as a default.  

You have two options here:
#### A) Enable polling
This requires some copy pasting in your own version of Atom,
1. Head to  `Settings`→`Atom-LaTeX`→`View Code`
2. Change the following line in `manager.coffee` 
```
@rootWatcher = chokidar.watch(root,{
        ignored: ///(|[\/\\])\.(?!#{watchFileExts.join("|").replace(/\./g,'')})///g
        })
```
to
```
 @rootWatcher = chokidar.watch(root,{
        ignored: ///(|[\/\\])\.(?!#{watchFileExts.join("|").replace(/\./g,'')})///g
        usePolling:true
        })
```
3. Reload Atom (<kbd>`ctr`</kbd>+<kbd>`shift`</kbd>+<kbd>`F5`</kbd>)  
4. Profit!? :-)

#### B) Disable the watcher
You could disable the watcher module, (albeit at the cost of more filesystem IO operations). To do this, add a `disable_watcher:true` to your `config.cson` (Found from `File`→`Config...`) under the Atom-Latex object - something like:
```
  "atom-latex":
    bibtex: "biber"
    disable_watcher: true
```

**Comment by fkjogu** [comment]
**A)** does not work, however **B)** does. When you talk about polling, are you refering to `epoll` async I/O, like inotify? What exactly happens, when disabling the watcher? And what happens, if I try to enable polling on a network mount?

**Comment by ashthespy** [comment]
When utilising the watcher, all parsing for the autocomplete (commands, citations, references) are performed only when the files are changed by events fired by the watcher.

When disabled, each autocomplete prompt (say typing `\`) results in all the dependent files parsed for commands,citations and references. 

About the polling, as I understood it, the default implementation of `chokidar` uses `fs.watch()` that does indeed utilise `inotify`. However, this does not work reliably on network drives.
When the `usePolling` flag is set, `fs.watchFile()` is utilised instead which queries the target `fstats` at a set  interval and fires the callbacks when it detects changes.  However, I would not pretend to be the expert here and direct you to https://github.com/paulmillr/chokidar#performance which covers it in more detail! :-)

**Comment by fkjogu** [comment]
I guess you were missing a comma in the end of the line before `usePolling: true`. But this still does not work. You might want to consider exposing `disable_watcher` to the settings dialogue as a workaround. It seems to work fine enough at the moment.

**Comment by fkjogu** [comment]
I'm not sure which mechanism the Visual Studio Code pendant https://github.com/James-Yu/LaTeX-Workshop uses, since this works out of the box.

**Comment by ashthespy** [comment]
Coffeescript doesn't require the commas while defining objects.
I shall try setting up a network drive and testing some more in the coming days, and get to the bottom of this :-)

Interesting observation about LaTeX-Workshop - James uses the same `chokidar` module as well, I'd reckon a guess that because only individual files (`fs.watchFile()` polling based method) are watched, while here the entire folder is watched (`fs.watch()` based method) this doesn't work out of the box. 
But again, I am not sure, and will do some digging.

**Comment by ashthespy** [comment]
Closing this issue in favour of the Option B - `disable_watcher` solution. 
We should switch over to the Atom native file system watcher soon either way!
