### ISSUE TITLE
Pdf Viewer closes on build

### ISSUE THREAD

**Issue by sanalphatau** [James-Yu/Atom-LaTeX#109]
When using the preview in new tab option and then building a latex file the preview tab closes. Before the tab would update with the new pdf once the build was complete. 

Apologies if I'm doing something silly.

Atom 1.19.5
Atom-latex 0.8.1

**Comment by ashthespy** [comment]
Need more info here to help debug :-)
Could you post your Atom-LaTeX settings? (From `File'→'Config...`)
Any interesting stuff doing on in the debug console? (<kbd>`ctr`</kbd>+<kbd>`shift`</kbd>+<kbd>`i`</kbd>)

**Comment by sanalphatau** [comment]
I have traced it back to having the pdf open in an external viewer at the same time. The expected behaviour is maintained if you enable focus on viewer as well. Then you can build the file and have a tab preview as well as the pdf open in an external viewer.

Nothing happening in the console that I can see beyond the usual build outputs.

**Comment by ashthespy** [comment]
So as I understood, you are no longer facing this issue when you close the pdf in the external viewer? 
Interesting, as I could not not reproduce the behaviour with both Foxit and Adobe Acrobat, my viewer tab refreshes fine, but displays only the old pdf as expected. 
Btw, I am unsure what external pdf viewer you use, but normally you'd run into 
```
xdvipdfmx:fatal: Unable to open "Test.pdf".

Output file removed.
 )
Error 1 (driver return code) generating output;
file Test.pdf may not be valid.
```
Which is true as the file is open in the external viewer.

**Comment by ashthespy** [comment]
Closing this issue, feel free to comment it you are still facing issues!
