### ISSUE TITLE
Input of $ character

### ISSUE THREAD

**Issue by johschmitz** [James-Yu/Atom-LaTeX#11]
There is a problem with `$` and `$$`
When `$` is input next to a letter there should be no automatic second `$`added by the system.
This is because sometime one wants to add a forgotten `$` in front or at the end of an equation in the middle of the text and then it is super annoying to remove the second `$` that automatically pops up all the time.
Only when a space is preceding AND a space or newline is following the cursor, the pattern `$<cursor_here>$` should be executed.

Please also compare with `{}`, however this case is slightly different.

**Comment by James-Yu** [comment]
I agree this is a useful fix. Will work on that.

**Comment by johschmitz** [comment]
I installed the 0.6.0 update today but it still seems to not work.
example:
before: `<cursor_here>equation`
after: `$<cursor_here>$equation`

**Comment by James-Yu** [comment]
The atom version will wait for some days to see the update. Ref #13.

You can read the readme for cutting edge changes installation.
