### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by Rocknpools** [James-Yu/Atom-LaTeX#112]
[Enter steps to reproduce:]

1. Buid a latex file without defining a root(it takes the root file correctly and build it as well but raise this Error)

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of undefined

```
At C:\Users\pas\.atom\packages\atom-latex\lib\autocomplete\citation.coffee:74

TypeError: Cannot read property 'substring' of undefined
    at Citation.module.exports.Citation.splitBibItem (/packages/atom-latex/lib/autocomplete/citation.coffee:74:16)
    at Citation.module.exports.Citation.getBibItems (/packages/atom-latex/lib/autocomplete/citation.coffee:51:21)
    at /packages/atom-latex/lib/manager.coffee:278:34)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/atom-latex/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/packages/atom-latex/node_modules/chokidar/index.js:238:5)
    at FSWatcher.NodeFsHandler._handleFile (/packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:275:10)
    at /packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-latex 0.8.1 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
expose 0.14.0 
highlight-selected 0.13.1 
imdone-atom 2.2.7 
language-matlab 0.2.1 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
multi-wrap-guide 1.0.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-atom-syntax 2.1.0 
northem-atom-ui 2.1.0 
northem-dark-atom-syntax 2.1.0 
northem-dark-atom-ui 2.1.0 
northem-light-atom-syntax 2.1.0 
northem-light-atom-ui 2.1.1 
project-manager 3.3.5 
tool-bar 1.1.0 
tool-bar-atom 1.7.0 
```

**Comment by ashthespy** [comment]
Could you recheck your `.bib` file?  Or share a MWE `.bib` file that reproduces this error?
I am guessing there will be an unexpected bibLaTeX syntax as in #67.  I have implemented a more meaningful error in https://github.com/James-Yu/Atom-LaTeX/commit/aa0435b911c2fe28b217bff3839d42fe5076e734 that should be in the next version :-)

**Comment by Rocknpools** [comment]
hi here is my .bib file(it comes from IEEE)
[IEEEexample.zip](https://github.com/James-Yu/Atom-LaTeX/files/1298945/IEEEexample.zip)

**Comment by ashthespy** [comment]
Can't find anything wrong with the `bib` file, do you have a MWE that threw this error?

**Comment by dpo** [comment]
I have this issue as well.

**Comment by ashthespy** [comment]
@dpo Issue report please! :-)

**Comment by ashthespy** [comment]
@dpo , @Rocknpools  Any updates?

**Comment by dpo** [comment]
I'll post the issue report the next time this comes up.

**Comment by ashthespy** [comment]
I will close this for now, feel free to comment if you face this issue again!
