### ISSUE TITLE
Zooming the preview document sometimes stops working

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#115]
It's a bit strange, but sometimes the zoom functionality of the viewer stops working. Document size remains the same regardless what I do with ctrl+mousewheel, +/- keys or the buttons and zoom select field in the tool bar. I need to close the viewer and reopen it to get back the zoom functionality. I have not found a reliable way to reproduce the issue yet. But it happens occasionally. Any other debug steps I could perform?

EDIT: maybe the in-repo bundled pdf.js dependency needs an update?!

**Comment by ashthespy** [comment]
While playing around more with `PDFjs`, I found that setting enabling webGL resulted in MUCH faster render times, and general overall smoothness. 
See if it helps in your case? 
Can be found in line 367  of `viewer.js` (`"enableWebGL": true`)

**Comment by exploide** [comment]
Looks a bit smoother. The problem is that the zoom issue isn't clearly reproducible. It only happens occasionally. I would propose that once the update with the pdfjs-dist dependency is out, I will comment here if I encounter the problem again. If not, after 2 weeks we could assume that the issue is gone with the updated dependency, so this issue can be closed. :S

**Comment by ashthespy** [comment]
Will close this for now, but please do comment if you are still facing issues!
