### ISSUE TITLE
Adding keybindings for \textbf{} and \textit{}

### ISSUE THREAD

**Issue by anonbnr** [James-Yu/Atom-LaTeX#119]
It would be pretty neat to have ^b for \textbf{} and ^i for \textit{} commands with the cursor positioned (à la sharelatex) in between the brackets instead of having to write them down every time and worrying about setting configuration files to get this done. I would've done it myself, but I have not much experience on how it can be done.

Thanks and cheers!

**Comment by ashthespy** [comment]
I am a bit apprehensive of overriding peoples default key bindings. For example, the logical <kbd>`ctrl`</kbd>+<kbd>`b`</kbd> for **bold** would mess with the default atom keybinding to the `fuzzy-finder:toggle-buffer-finder` on Windows. 

That being said, Atom is 'A hackable text editor' so, you could add this to your `init.coffee` file to achieve what you desire:
```
# Custom LaTeX commands for fontStyle
atom.commands.add 'atom-text-editor', 'user-custom:latex-bold', -> # Defines a command to work within the TextEditor.
# Exit if no active editor, with tex grammar is found
  return unless (editor = atom.workspace.getActiveTextEditor()) && ('text.tex' not in editor.getGrammar().scopeName)
  selection = editor.getSelectedText() # Get the selection(s).
  # insertText() replaces the whole selection. The options argument makes sure that the resulting text is selected.
  editor.insertText("\\textbf{#{selection}}",{select: true})
```
This command can then be toggled from the command pallet, or you can add the following to your keymap file:
```
'atom-text-editor':
  'ctrl-b':'user-custom:latex-bold'
```

However, if more people want this functionality by default, shall add it by default to the package.

**Comment by dpo** [comment]
An alternative that doesn't require a key binding is to define snippets. Go to Atom > Snippets... and enter the following
```cson
'.text.tex.latex':
  'textbf':
    'prefix': 'bf'
    'body': '\\\\textbf{$1}'

  'textit':
    'prefix': 'it'
    'body': '\\\\textit{$1}'
```
Save, open a `.tex` file, enter `bf` or `it` and hit TAB. You'll have `\textbf{}` or `\textit{}` with the cursor positioned between the curly braces.

**Comment by ashthespy** [comment]
@dpo I think what @anonbnr  requested was to wrap a selected word with the command, rather than a autocomplete :-)

**Comment by dpo** [comment]
@ashthespy I see no indication of that in the OP's message but either way, I don't feel this sort of minor hack should be part of atom-latex.

**Comment by ashthespy** [comment]
I stand corrected - OP indeed wants only an autocomplete. 

I am going to close this issue. Suitable options have been provided, and I too feel this isn't a core package functionality.
