### ISSUE TITLE
Focus change

### ISSUE THREAD

**Issue by JonathanGallagher** [James-Yu/Atom-LaTeX#12]
Hi,

How hard would it be to allow for focus changing from pdf-view to the editor.  Currently, Ctrl-Clicking
in the pdf-view window correctly changes the caret position, but it does not jump to the editor.  I can see some people not wanting this behaviour anyway!  However, I would love this, and wouldn't mind trying to make a toggle-able focus switch -- much like in the sublime-text latex tools plugin.  However, I have no experience with atom development; could you point me towards the file(s) I would need to edit?

**Comment by James-Yu** [comment]
In fact I have tried to implement this but have no good result. This plugin calls electron API to create a new window, yet I am not familiar with electron interfaces. Will look into that.

All viewer related codes exist in `viewer` file and synctex related in `locator` file. Thanks all the same.

**Comment by James-Yu** [comment]
A dirty implementation of the said feature. Yet it works!
