### ISSUE TITLE
Support for listings package

### ISSUE THREAD

**Issue by lucbouge** [James-Yu/Atom-LaTeX#120]
Dear @ashthespy,

I am an intensive user of LaTeX (actually, `pdflatex` from the `texlive` distribution) to write papers about programming.

My LaTeX code includes a large number of code snippets, formatted with the `listings` package, see https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings.

It looks like the `lstlisting` environment is not recognized by your Atom style.  Is it handled? 

It is especially important that the beautifier does not modifies the indentation there, and that the LaTeX keywords are not highlighted within this environment, as any arbitrary language can be used there.

Best regards,

Luc.

**Comment by ashthespy** [comment]
Hi Luc,

The package already supports `lstlisting` environment.

Could I request you to:
1. Provide a screenshot of the issue you are facing? 
2. With your cursor in the  `lstlisting` environment, launch the Command pallet (<kbd>Ctr</kbd>+ <kbd>Shift</kbd> + <kbd>P</kbd>) and run `Editor: Log Cursor Scope` and share the scopes you see?

**Comment by ashthespy** [comment]
@lucbouge any updates? I am closing this issue as inactive for now - feel free to comment, and shall open it again.

**Comment by BambOoxX** [comment]
@ashthespy  I am currently facing an issue with the `lstlisting` environment. The formatting of the environment does not follow the same rules as say the `equation` environment . See the screenshot below.

![image](https://user-images.githubusercontent.com/42067365/43644027-8aa2a498-972d-11e8-83ee-2a3a0dbb9153.png)

**Comment by mark-fangzhou-xie** [comment]
@ashthespy Hi, I am currently having the same problem.
![image](https://user-images.githubusercontent.com/45321577/57039084-afc6a180-6c29-11e9-94d0-0c79661540e0.png)
`Scopes at Cursor

text.tex.latex
meta.embedded.block.generic
meta.function.embedded.latex
`
I wonder if I haven't configured the right settings.
