### ISSUE TITLE
Sync cursor position

### ISSUE THREAD

**Issue by mame98** [James-Yu/Atom-LaTeX#124]
TeXStudio offers the options to sync the cursor position between both (source/pdf) documents. You can choose if you only want it in one direction or in both.

I would love to see such a feaute in this plugin, any plans to do this?

**Comment by ashthespy** [comment]
Um, you mean [SyncTeX](https://github.com/James-Yu/Atom-LaTeX#usage)?

**Comment by mame98** [comment]
Well, turns out I'm just to stupid :laughing:

Nevermind, thank you :+1:
