### ISSUE TITLE
Add support for subfiles

### ISSUE THREAD

**Issue by NoxMortem** [James-Yu/Atom-LaTeX#125]
Texmaker can sync subfiles by marking one file as current document. When working on large tex documents split across multiple files this is a must have feature for synctex to work properly.

**Comment by ashthespy** [comment]
What exactly do you mean by 'sync subfiles'?

**Comment by NoxMortem** [comment]
Sorry the issue can be closed. I missed the part that synctex is missing from miktex but following the links on the landing page about synctex lead me to: https://tex.stackexchange.com/questions/338078/how-to-get-synctex-for-windows-to-allow-atom-pdf-view-to-synch#comment877274_338117 and now it works :)

If you use miktex you need to add synctex.
