### ISSUE TITLE
Viewer has problems with tikz drawings from moderntimeline

### ISSUE THREAD

**Issue by michaelaye** [James-Yu/Atom-LaTeX#127]
In this screenshot you see a timeline I created with moderntimeline, which is using tikz for these drawings.
On the left is the rendering of this PDF previewer, on the right, macOS Preview.

![screenshot 2017-11-16 10 44 08](https://user-images.githubusercontent.com/69774/32906815-5a5ef8ac-cabb-11e7-9311-3d9e8c5f9292.png)

I'm running atom-latex 0.8.2 on Atom 1.22.1 on macOSX 10.12.6

**Comment by michaelaye** [comment]
FYI, the above time bars are created with \tlcventry, while the one dot is a one-time spot created with \tldatecventry
This library is a companion library to `moderncv`.

**Comment by ashthespy** [comment]
@michaelaye could you share a MWE pdf?

**Comment by michaelaye** [comment]
here's a MWE:

```latex
\documentclass{moderncv}
\moderncvstyle{classic}

% timeline package
\usepackage[firstyear=1995,lastyear=2020]{moderntimeline}

% Personal Information
\name{MWE}{}
\begin{document}
\tlcventry{2010}{0}{}{}{}{}{}
\end{document}
```

**Comment by ashthespy** [comment]
@michaelaye  I am able to reproduce it, with our current version of  the viewer `[1.5 pdfTeX-1.40.18 / LaTeX with 'moderncv' package] (PDF.js: 1.9.426)` The issue goes away on zooming in to 150%. However, I agree this is not the desired behaviour. 

I just ran a quick test by launching the pdf with the version of pdfjs that is shipped with the current Firefox `[1.5 pdfTeX-1.40.18 / LaTeX with 'moderncv' package] (PDF.js: 1.9.583 [WebGL])` and it seems to work fine.  However, I recall we had [issues earlier](https://github.com/James-Yu/Atom-LaTeX/pull/117) with bumping up the version of `pdfjs` that was packaged with this package.

**Comment by ashthespy** [comment]
@michaelaye I stumbled upon a workaround for your specific issue the other day - try changing the [`renderer`](https://github.com/James-Yu/Atom-LaTeX/blob/master/viewer/viewer.js#L377) from `canvas` to `svg`. I am unsure about the impact on performance - but it renders the graphics properly.

**Comment by michaelaye** [comment]
Thanks, good to know. In the meantime I changed my editor to VSCode due to its superior speed, but interestingly, it has the same built-in rendering problem. ;)

**Comment by ashthespy** [comment]
I was just reading up - it would seem that there are some sporadic issues with electron and `canvas` rendering - but nothing concrete. Atom for example is currently based on chrome `56.0.2924.87` so I hope that with never versions, there is better support.


Offtopic - but is VSCode really that much faster?

**Comment by michaelaye** [comment]
Offtopic - oh yes, especially if you have as many plugins/extensions as me. ;) And their Latex plugin is also very powerful, and the Python plugin is now officially done by Microsoft, so they have people power behind it. Honestly, it's the first time in a LOOONG time that I'm pleased by a Microsoft product.. ;)

**Comment by ashthespy** [comment]
Ah - I have it installed, but use the Atom 'text editor' feel more compared with VSCode. 
Anyway - I shall close this issue for now -- and keep tabs on chrome updates and canvas rendering.

Cheers!
