### ISSUE TITLE
Latex compiler setting is not saved

### ISSUE THREAD

**Issue by cnasikas** [James-Yu/Atom-LaTeX#138]
I am trying to change Latex compiler to `xelatex` but the settings don't seem to be updated. 

When I compile the execution command is: 
```
> latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf thesis

Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
```

With the following package error (that's why I need xelatex):

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
/usr/local/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec.sty:28: Fatal fo
ntspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX.
! 
! You must change your typesetting engine to, e.g., "xelatex" or
! "lualatex"instead of plain "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```

**OS:** macOS High Sierra 10.13.3
**Atom:** 1.23.3
**Latexmk:** 4.45

Everything compiles fine If I run:
```

xelatex thesis
bibtex thesis
xelatex thesis
xelatex thesis
```
If you need me to provide more information feel free to inform me.

Thanks a lot for this great plugin

EDIT

I deactivate **Build Latex after saving** and the setting was saved and worked.

**Comment by cnasikas** [comment]
Also after the first compilation (even with errors) I can't build anymore. I get latexmk skipped building process. So I have to delete all non tex files and try to compile again.

**Comment by cnasikas** [comment]
I update latexmk to 4.55. When I run from the terminal the following command:

`latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -xelatex thesis`

it compiles, without error. When I build inside Atom is still ignoring the `xelatex` compiler and uses `pdflatex`

**Comment by ashthespy** [comment]
@cnasikas How have you set up your [toolchain](https://github.com/James-Yu/Atom-LaTeX#-setting-up-a-toolchain)?

**Comment by cnasikas** [comment]
@ashthespy The default. I haven't change anything. 

`%TEX %ARG %DOC && %BIB %DOC && %TEX %ARG %DOC && %TEX %ARG %DOC`

**Comment by cnasikas** [comment]
I have read it but at the moment I couldn't understand why setting the Latex compiler to `xelatex` not working. Thanks to you I understood that `latexmk` executes all necessary steps in one command and is a totally different program that it is used instead of running `xelatex -> bibtext -> xelatex -> xelatex`

**Comment by ashthespy** [comment]
Yes and no :-) 
`Latexmk` is an engine/builder helper - that automates the building process. It incorporates some smarts to try and minimise the compilation time by building only changed files etc.

But for your "issue" 
When you set the compiler to `xelatex` in the settings page, you need to also change the `Toolchain to use` from `auto` to `custom`

**Comment by cnasikas** [comment]
I see. Thanks a lot for your help!!
