### ISSUE TITLE
BibTex complains

### ISSUE THREAD

**Issue by apeltzer** [James-Yu/Atom-LaTeX#14]
Hi, unfortunately I always get an error with bibtex (even though I don't have any bibtex/bibliography in my tex file)

`Command failed: /Library/TeX/texbin/bibtex file
DismissShow build log
`

and this is in the logfile

`> /Library/TeX/texbin/bibtex 0_PraktikumPlan

This is BibTeX, Version 0.99d (TeX Live 2016)
The top-level auxiliary file: file.aux
I found no \citation commands---while reading file file.aux
I found no \bibdata command---while reading file file.aux
I found no \bibstyle command---while reading file file.aux
(There were 3 error messages)
`

Well, this document has no bibliography at all, so why starting bibtex here?

**Comment by James-Yu** [comment]
You do need to CUSTOMIZE the toolchain if selected that option. Otherwise auto or latexmk should work fine.

**Comment by mabuimo** [comment]
I had the same issue that @apeltzer described.

**Comment by ashthespy** [comment]
@mabuimo  you need to remove BibTeX from the default toolchain.

**Comment by MeaningOf42** [comment]
@ashthespy how exactly do I remove bibTex from the default tool chain?

**Comment by ashthespy** [comment]
@MeaningOf42 
Change the [default toolchain](https://github.com/James-Yu/Atom-LaTeX#-setting-up-a-toolchain) entry to something like: 
`%TEX %ARG %DOC && %TEX %ARG %DOC`

**Comment by MeaningOf42** [comment]
@ashthespy Thanks for help. By the default toolchain do you mean the toolchain field in the projects .latexconfig or is there a way of setting the default toolchain for every project (This would be more useful).

I set the .latexconfig toolchain to your suggestion and the preview now shows, however the same errors are thrown.

The only two files in my project that I created (others were created by latex) are:

+ test.tex:
```
\documentclass{article}
\begin{document}
  test 12
\end{document}
```
+ and .latexconfig:
```
{
  "root" : "test.tex",
  "toolchain" : "%TEX %ARG %DOC && %TEX %ARG %DOC",
  "latex_ext": [".tikz", ".Rnw"]
}
```

any idea what the issue is?

**Comment by ashthespy** [comment]
@MeaningOf42 
The `.latexconfig` is indeed meant for per-project basis configuration. The default toolchain settings can be found on the package's settings page. E.g `Toolchain to use` and `Custom toolchain commands` setting fields - they should be pretty self explanatory ;-) 
Either way - what is the error you are seeing?

**Comment by MeaningOf42** [comment]
I changed the custom tool chain commands, and restarted atom, and I am no longer seeing the error (error was same as OP's). Thanks for your help.

**Comment by MeaningOf42** [comment]
Just a quick quest though, should the default tool chain use bibtex? To me it would make more sense to not include it by default, then allow users to add it if they want, rather than forcing people to opt out. I don't know though, I may be far from the norm in not wanting to use bibtex.

**Comment by ashthespy** [comment]
> Just a quick quest though, should the default tool chain use bibtex? To me it would make more sense to not include it by default, then allow users to add it if they want, rather than forcing people to opt out. I don't know though, I may be far from the norm in not wanting to use bibtex.

The package's default option is to use `latexmk`, that automagically decides what toolchain to run, checking if `bibtex` is required or not based on each project. The fallback is the hard coded custom option if `latexmk` isn't found, where the quite standard toolchain is chosen.

**Comment by marcusnewton1** [comment]
> 
> 
> @MeaningOf42
> Change the [default toolchain](https://github.com/James-Yu/Atom-LaTeX#-setting-up-a-toolchain) entry to something like:
> `%TEX %ARG %DOC && %TEX %ARG %DOC`

Thanks, this solved the issue for me.
