### ISSUE TITLE
Disable adding <> to bracket-matcher

### ISSUE THREAD

**Issue by StevenClontz** [James-Yu/Atom-LaTeX#140]
It would be ideal if there was a way to disable bracket matching `<` with `>` automatically. Right now I have to add the following to the bottom of `~/.atom/config.cson` to override the package setting:

```
".latex.tex.text":
  "bracket-matcher":
    autocompleteCharacters: [
      "$$"
      "``"
      "{}"
      "()"
      "[]"
      "«»"
      "\"\""
      "''"
    ]
```

**Comment by ashthespy** [comment]
Could I ask the rational behind disabling it? 
I don't think that this is something that should be brought into the main settings page, as it's a rather niche use case. Tweaking your own `config.cson` as you have is much cleaner for what you want to achieve.

**Comment by StevenClontz** [comment]
I guess I'm unaware of the usage of `<>` as brackets in LaTeX. It seems reasonable to me that they might be more commonly used in typesetting inequalities such as `1<2` than as brackets, since `\langle\rangle` are the appropriate commands for angle brackets.

The other related issue is the lack of documentation that this package treats them as brackets. I expected `$$` but was surprised to see `<>`, which I don't think appears in any other LaTeX package I've used. If you don't want to expose an option to customize the brackets defined by this package (I don't know how easy that is), it'd be convenient to add a note to the readme about what's being done and how to customize them.

**Comment by ashthespy** [comment]
Hmm, makes sense - have disabled the matching of `<>` and `«»`. 
Unfortunately, atom's [bracket-matcher](https://github.com/atom/bracket-matcher) doesn't let you distinguish between pairs to auto close, and pairs to wrap selected text with currently, which would have been ideal.
