### ISSUE TITLE
linter disabled whne using this package

### ISSUE THREAD

**Issue by stakaz** [James-Yu/Atom-LaTeX#143]
Hello, when I use the package, I have no linter panel on the bottom and e. g. `linter-spell-latex` does not work. Can you confirm this issue?

Some other linter packages work (`linter-write-good` and `linter-alex`), but still, no panel is visible. 

I think that at least for `linter-spell-latex` the problem is that it depends on `language-latex` which is not used by `atom-latex`.

**Comment by stakaz** [comment]
Ok, I have found a solution:

adding `"atom-latex:grammar-used"` to `"activationHooks"` section in `package.json` brings back the panel and spell checking works fine.


I already posted to `linter-spell-latex` here: https://github.com/AtomLinter/linter-spell-latex/issues/31

**Comment by ashthespy** [comment]
Will close given the upstream issue :-)
