### ISSUE TITLE
Auto-completion for citations not providing suggestions

### ISSUE THREAD

**Issue by vqv** [James-Yu/Atom-LaTeX#144]
MRE 

1. Use the gist here: https://gist.github.com/anonymous/59292e9b8aa1d214fa75cc27107a8add
2. Type `\cite{s`

I did some debugging and it looks like there are two issues:

1. resetBibItems() is being called prematurely [here](https://github.com/James-Yu/Atom-LaTeX/blob/0ff0573b3ae6926291544f5b4b0a16a8f5a37e34/lib/manager.coffee#L158)
2. When autocompleting with a prefix "s" in the MRE above, Citation.provide() tries to look for cached suggestions [here](https://github.com/James-Yu/Atom-LaTeX/blob/0ff0573b3ae6926291544f5b4b0a16a8f5a37e34/lib/autocomplete/citation.coffee#L13), but they are empty the first time.

Removing the line in (1) and changing the line in (2) to 

```
    if prefix.length > 0 && @suggestions.length > 0
```

seems to "fix" things, but may break others, but I'm not familiar enough with the codebase to make any better suggestions.

**Comment by ashthespy** [comment]
Hi!
I don't seem to replicate your issues:
![cite_issues](https://user-images.githubusercontent.com/16233271/37481013-edc0cd50-2880-11e8-933b-84b8c89af26a.gif)

What are your autocomplete settings like? I am on the default settings (I think):
```
Suggestions List Follower: Word
Default Provider: Subsequence
```

**Comment by vqv** [comment]
1. Reload the window.  That should clear out the suggestions cache.
2. No suggestions when using \cite{}
3. Save the .bib file to trigger the watcher
4. Suggestions now appear when using \cite{}

![atom-latex](https://user-images.githubusercontent.com/867637/37482585-f2d7a60e-285a-11e8-8d9b-aac1e3b0b19d.gif)

**Comment by ashthespy** [comment]
Interesting behaviour. 

1. Could I ask what provider you use with with `autocomplete-plus`? 
2. Could you counter check that the `.bib` file is getting parsed the first time via the [`add` event](https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/manager.coffee#L278)? It's indeed erratic behaviour, it should parse the bib file without you having to save it to trigger a `change` event. 
2a. Does the issue persist if you disable the watcher by adding a `disable_watcher:true` to your `config.cson` (Found from `File`→`Config...`) under Atom-Latex:

```
  "atom-latex":
    bibtex: "biber"
    disable_watcher: true
```

Side note: Adding some logging to the package has been on the todo list for quite a while now.  The framework is there, just need to add the events. Maybe high time to dig out that branch and finish it!

**Comment by ashthespy** [comment]
Closing given the silence, feel free to post when you have more info!
