### ISSUE TITLE
Add ConText compilation support

### ISSUE THREAD

**Issue by mrmayfield** [James-Yu/Atom-LaTeX#148]
It would be nice to add support for ConText compilation. Atom-LaTeX already works well for developing ConText documents (with the addition of a ConText grammar plugin), but you have to drop to the command line to compile the document. Could you add in ConText support through either an option or a "magic comment"? (TeXShop compiles ConText automatically when someone places the comment "% !TeX program = ConText" at the start of a document.)

So you don't have to look up the context compilation commands, to compile a Context document from the command line you type "context *filename*". For compilation with synctex you type "context --synctex *filename*".

Thanks in advance for considering this request.

**Comment by ashthespy** [comment]
@mrmayfield  You can use any [arbitrary toolchain](https://github.com/James-Yu/Atom-LaTeX#-setting-up-a-toolchain) with this package (incidently one of the reasons I started using it ;-))  


#### Option 1: Use ConText as the predefined compiler for all projects
Head to the package settings, and add your compiler in the `custom toolchain` setting. E.g
`context --synctex  %DOC` 

#### Option 2: Define a custom `.latexcfg` only for ConText documents. 
Drop in a `.latexcfg` in the root of your project dir with something like this:
```
{
  "root" : "\path\to\root\file.tex",
  "toolchain" : "context --synctex %DOC",
}
```

**Comment by mrmayfield** [comment]
Thanks! I appreciate the information and the good work you did on the package's flexibility.

**Comment by ashthespy** [comment]
All due goes to James, the package author - I just help maintain it!

Cheers,
