### ISSUE TITLE
 jobName is not working

### ISSUE THREAD

**Issue by devassyhere** [James-Yu/Atom-LaTeX#151]
![screen shot 2018-04-23 at 15 05 46](https://user-images.githubusercontent.com/1451121/39128344-d56b552c-4707-11e8-852e-8f5cb2964281.png)

I am trying to use the jobName magic command, and I cannot get it to work.

I am using Atom 1.26.0 x64 in Mac
![screen shot 2018-04-23 at 15 07 17](https://user-images.githubusercontent.com/1451121/39128430-09d9715e-4708-11e8-9859-6b926459a647.png)

Please do get back if more information is required!

**Comment by ashthespy** [comment]
There is currently no support for these TeX directives. 
A workaround is to define it manually in your toolchain with something like `-jobname=foo`

**Comment by devassyhere** [comment]
:) ok!
I thought since it was mentioned in the "Overriding Build Settings" section, it might be supported!

**Comment by ashthespy** [comment]
Hmm, I am pretty sure you are confusing another package with this package. We don't have any 'Overriding Build Settings' section!

**Comment by devassyhere** [comment]
Yes you are right! my bad!
