### ISSUE TITLE
Automatically detect XeLaTeX?

### ISSUE THREAD

**Issue by kellertuer** [James-Yu/Atom-LaTeX#154]
I am just starting to use atom for LaTeX, and the Atom-LaTeX package is great for a start. However, I am usually writing documents using pdflatex but talks (due to the awesome metropolis theme) with xelatex. Of course I can change the settings whenever I switch working on a project, but:

Is there a way to detect that automatically?
For one, many editors handle the

   %! TEX program = latexmk -xelatex

line to compile that specific file with xelatex; other helpers (for example in TextMate, which was my previous editor) the compiler to choose was based on whether fontspec or xunicode was loaded (both require to use xelatex) and used that as an indicator.

Would it be possible to add this automatism to atom-LaTeX as well?

**Comment by simon123h** [comment]
As an alternative for the _magic comment_ line you proposed:
Atom-LaTeX searches for a `.latexcfg` file in your working directory, in which you can specify your compiler toolchain. An example is given in the end of [Readme.md](https://github.com/James-Yu/Atom-LaTeX#-set-per-project-latex-toolchain).
This doesn't fulfill your request, but might fix your workflow.

**Comment by kellertuer** [comment]
But...I like magic!
Jokes aside, you're right having two `.latexcfg` s (or at least one for my xelatex cases) would yield the result I want to have, namely that compiling a project with xelatex (prepared with said config) would work without changing the settings.
“With magic” (i.e. without copying a config to each project requiring xelatex) would still be nicer :) but thanks for the fix for my workflow.

**Comment by ashthespy** [comment]
@kellertuer This is indeed a "todo" feature that I need to find time to implement (PR's welcome!)

Since you like magic - have a look at [`arara`](https://www.ctan.org/pkg/arara?lang=en) - then choosing your per project toolchain is as simple as
```
% arara: xelatex: { shell : yes }
% arara: bibtex
% arara: xelatex: { shell : yes }
% arara: xelatex: { shell : yes }
```

**Comment by kellertuer** [comment]
Thanks for the info, I've never tried arara, but I think I'll give it a try, since that really looks like what I'd like to have (when it's not possible to have that completely automated) :)
I've never worked on Atom Plugins/Packages, so I am not of help for your PR.

**Comment by ashthespy** [comment]
Closing this in favour of above issue.

**Comment by kellertuer** [comment]
As a (final) remark, the arara package does the job for now, though I switched also to

     % arara: xelatex: {synctex: yes, action: nonstopmode, options: "-file-line-error-style", shell: yes}

instead of just activating the shell.
