### ISSUE TITLE
Building in atom-latex order of magnitude slower than command line

### ISSUE THREAD

**Issue by SiriusStarr** [James-Yu/Atom-LaTeX#156]
I'm sure I'm being stupid somewhere here, but I can't for the life of me figure out why compiling in atom-latex is almost unusably slow.  Building my document from a clean takes 80-85 seconds and a re-build without cleaning takes 25-30 seconds.  Just executing the same build command:
`latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf Document`
on the command line takes 17 seconds for a full build and about 6 for a re-build.  I would expect some amount of overhead, obviously, but a 4-5 fold increase in compilation time seems like something is wrong somewhere.  How can I track this down?

**Comment by SiriusStarr** [comment]
It should be noted that this doesn't seem confined to "large" documents.  A minimal file with 20 paragraphs of lorem ipsum takes ~1300 ms to build in atom-latex and ~400 ms on the command line, and adding a very simple TikZ drawing increases it to ~2100ms in atom-latex and only about 500 ms on the command line.

**Comment by ashthespy** [comment]
@SiriusStarr I don't seem to be able to reproduce this - I have tired on quite a few documents.  Of course there is some overhead - but not the magnitude you mention.  I typically have ~10% overhead compared to directly building off the command line. 
However, this is most likely something system specific - so I can't help you much.
Some ideas though:
1. Check the dev console if you have any errors.
2. Take a look at your atom packages, if you have a lot of them - try a minimal number of packages and see if that improves the times.

**Comment by SiriusStarr** [comment]
Nothing noteworthy on the console, and I don't think it's related to my packages, as I've gotten a few more LaTeX files up into several hundred page range with them still compiling rapidly.  I've come across two documents that bog down like crazy; unfortunately, they cannot be publicly disseminated.  I'll try to pare down an MWE out of them, or chalk it up to the wonkiness of complicated LaTeX if I can't.  XD

Thanks for taking a look; I'll report back if I can isolate something more concrete.

**Comment by ashthespy** [comment]
@SiriusStarr Please feel free to add any new info - shall open up the issue again then! :-)
