### ISSUE TITLE
Automatically disable the panel

### ISSUE THREAD

**Issue by BigfootN** [James-Yu/Atom-LaTeX#157]
Hello,

When I edit a `.tex` file, the panel is automatically enabled. Is there a way to disable it definitely without having to do it manually every time ?

Thank you very much in advance.

**Comment by ashthespy** [comment]
Hi, 

There is no elegant way to do this right now, I will add an option in the next version :-)

**Comment by BigfootN** [comment]
Thank you very much for your answer

**Comment by gilbertohasnofb** [comment]
@ashthespy would it be possible to add this option to the package's Settings menu as a checkbox option? That makes it much easier for users to enable/disable it as opposed to having to manually edit your `config.cson`

**Comment by ashthespy** [comment]
@gilbertohasnofb Don't personally think it's worth the effort. It takes 10 seconds to copy paste it into your `config.cson`.. But your welcome to open up PR..

**Comment by gilbertohasnofb** [comment]
I know this is a minor thing that takes only a few seconds to copy and paste, but you need to know that this option exists in the first place. I think new users might appreciate the toggle box. I opened a PR here: https://github.com/ashthespy/Atom-LaTeX/pull/262
