### ISSUE TITLE
Error when building file with name containing whitespace

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#158]
When I try to build a file like `File with Whitespace.tex` the following error appears:

```
Command Failed: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf "File with Whitespace"
```

Executing the same command on commandline works. If I replace the whitespace with `_` it also works.

**Comment by ashthespy** [comment]
@exploide I don't seem to be able to reproduce this? Any other info that might help?

```
Step 1> latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf "Status Update"
Successfully built LaTeX in 5365 ms
```

**Comment by exploide** [comment]
Strange. But I also remember it worked in the past. Don't know what happened in the meantime.

- Fedora 28
- Atom 1.27.0
- Atom-LaTeX 0.8.4

Let me know if other information would be useful. I attached a screen recording:
![1526918901131](https://user-images.githubusercontent.com/5670236/40318005-7f197f96-5d23-11e8-9caa-000ecf7315cc.gif)

**Comment by ashthespy** [comment]
I will try reproducing with a virtual machine sometime this weekend. I don't have any ideas of the top of my head though.

**Comment by leonardopacciani** [comment]
I am having the exact same issue: if the file's name contains a space the build process fails (and I get the very same error of @exploide 's example:  _Error building LaTeX (code 11): Command Failed: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf "some file"_), but as soon as the space is removed everything works.

- OS: Ubuntu 18.04
- Atom version: 1.27.1
- atom-latex 0.8.4

**Comment by ashthespy** [comment]
I am sorry guys - I haven't had the time to debug this with a VM.  I shall try to allocate some time this week - are you all still facing this issue?

**Comment by exploide** [comment]
Yes, the problem is still present.

**Comment by ashthespy** [comment]
Found it the error. Apparently you don't have to escape the file name when passing it to [`cp.spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) for unix.

For a temporary fix, please navigate to your `lib/builder.coffee` (from Settings>Packages>Atom LaTeX>View code) and change
```
toolchain = cmd.split(' ') # Split into array of cmd + arguments
```
with 
```
# toolchain = cmd.split(' ') # Split into array of cmd + arguments
toolchain = cmd.match(/(?:[^\s"]+|"[^"]*")+/g).map((arg) -> arg.replace(/"/g,''))  # Split into array of cmd + arguments (un-escaping "" again)
```
 I will rewrite the builder to use an array of arguments instead of the around-the-bush method of how we currently build up the argument list.
