### ISSUE TITLE
Build Log does not show all warnings

### ISSUE THREAD

**Issue by sbdfh** [James-Yu/Atom-LaTeX#159]
Warnings of the following type are not picked up by the build log:

> Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 37.

and

> LaTeX Font Warning: Font shape 'OT1/cmr/bx/sc' undefined
(Font)              using 'OT1/cmr/bx/n' instead on input line 78.
LaTeX Font Warning: Some font shapes were not available, defaults substituted.

There seem to be two problems here. First, the parser regex for warnings is not searching for Font warnings (this can easily be fixed). The larger problem is that both warnings contain linebreaks. This means that the lines are broken shy of 80 characters, and thus are not merged back into one long line. I do not have a good idea how to fix this in the current line-wise parsing of the log. 
A quick fix might be to search lines that match
`/^((?:(?:Class|Package) \S+)|LaTeX (?: Font)?) (Warning|Info)/`
but not the whole latexWarn expression and the merge these with the following line. But this does not seem to be a robust fix of the problem.

**Comment by ashthespy** [comment]
The logparser could do with a rewrite - but I don't have much time these days, given that the package has reached a level where it's good enough for my everyday use ;-)

But, PR's are always welcome!
