### ISSUE TITLE
Focus minimized pdf viewer on build

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#16]
If the pdf preview window is already open but not in the foreground, it is not focused after the build process is finished. Would be cool if this would work the way that the preview window comes back to the foreground after the build command is triggered.

**Comment by James-Yu** [comment]
Good idea! Will check if the feature can be implemented.

**Comment by exploide** [comment]
@James-Yu thanks for considering this :)

Unfortunately, the pdf viewer isn't brought into focus at all since the 0.7.0 release. Even when building a pdf for the first time. Guess something went wrong. Let me know if you need further information.

**Comment by James-Yu** [comment]
The viewer window will be brought to the front, but the atom window will maintain focus. If the default viewer position is covered by that, it will not be shown.

Any suggestions on how the bring-to-top-but-not-focus feature should work? the viewer window should not gain focus after building because that will cause trouble for those who regularly press ctrl+s

**Comment by exploide** [comment]
Ah, I see. Misunderstood that feature. Mhh ok, we have people who don't want to be annoyed when pressing ctrl+s and we have people who want to immediately see the result when building the document.

What about a conditional behavior: Bring it to the front when the button is pressed or the build command is fired manually but not when the build is triggered after save?

**Comment by James-Yu** [comment]
I will think of both options. The first one might be not very intuitive as it is called `build` instead of `build and show`. Though nothing confirmed.

Thanks for the suggestions!

**Comment by exploide** [comment]
While writing... I just noticed that invoking the preview function from command pallet or shortcut works fine while clicking the magnifier icon has no effect when the preview window is already in the background. Guess this is related and should also be consistent.

**Comment by James-Yu** [comment]
Still not completely solved. Will introduce a new setting to control this behavior.

**Comment by James-Yu** [comment]
This should satisfies the most.

**Comment by exploide** [comment]
I would like to point out that this issue is back for a while. When the pdf viewer window is minimized, a new build will not focus the preview window. Pressing the magnifier icon also has no effect in this case.

Maybe you can reopen @ashthespy

**Comment by ashthespy** [comment]
@exploide I can't seem to reproduce this - any more details?

My settings:
```
  "atom-latex":
    build_after_save: false
    focus_viewer: true
    save_on_build: true
```
Both the preview and build buttons focus a minimised preview window in my case (`v0.8.1`)

**Comment by exploide** [comment]
Current settings:

```cson
  "atom-latex":
    build_after_save: false
    file_ext_to_clean: "*.aux, *.bbl, *.blg, *.idx, *.ind, *.lof, *.lot, *.out, *.toc, *.acn, *.acr, *.alg, *.glg, *.glo, *.gls, *.ist, *.fls, *.log, *.fdb_latexmk, *.bcf, *.run.xml, *.synctex.gz"
    focus_viewer: true
    hide_log_if_success: true
    latexmk_param: "-synctex=1 -interaction=nonstopmode -file-line-error -pdf -shell-escape"
    save_on_build: true
```

Version: atom-latex@0.8.1 with Atom 1.19.7

System: Fedora Linux with Cinnamon Desktop

Screencapture:

![1505151632106](https://user-images.githubusercontent.com/5670236/30288557-7148671c-9729-11e7-86bc-c19a21063fbe.gif)

**Comment by ashthespy** [comment]
@exploide  
Can you check if you get any errors in the dev console if you try to focus the window with either `atom_latex.latex.viewer.window.focus()` or `atom_latex.latex.viewer.window.show()`?

Unfortunately, this seems to be something system specific that I can't reproduce here (Win10/8) to debug.

**Comment by exploide** [comment]
`atom_latex.latex.viewer.window.focus()` returns `undefined` and nothing happens.

`atom_latex.latex.viewer.window.show()` also returns `undefined` but the viewer window comes to the front.

**Comment by ashthespy** [comment]
Seems `focus()` doesn't have the same behaviour across Linux and Windows platforms - will switch to [`show()`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winshow) as it 'Shows and gives focus to the window.' - what we want :-)
