### ISSUE TITLE
Cannot find the LaTeX root file with \begin{document}

### ISSUE THREAD

**Issue by gvdeynde** [James-Yu/Atom-LaTeX#160]
I use beamer for my course notes. In order to easily create the slides (with transittions) and handouts, I use the "three file setup":

File "course_slides.tex" contains only two lines:

\documentclass[10pt,t]{beamer}
\input{the_course.tex}

File "course_handouts.tex" contains only two lines:
\documentclass[10pt,t,handout]{beamer}
\input{the_course.tex}

File "the_course.tex" contains the course material:
[preamble]
\begin{document}
this is an interesting course
\end{document}

When I want to compile course_slides.tex, atom-latex fails by stating it cannot find the LaTeX root file and gives me three options. When I set the root file manually (with the home button, for example), atom-latex registers this, but fails with the same error as before. 

Does atom-latex check the root file for a "\begin{document}" line? I don't think this is a wanted feature in case the user sets the root file explictly.

**Comment by ashthespy** [comment]
Hi, 
The package follows a simple hierarchy to determine the [root file](https://github.com/James-Yu/Atom-LaTeX#setting-the-latex-root-file). It pareses files for the `\begin{document}` line only if no explicit root file is set. 
Once the file is manually set - it *should not* again parse all directory files. 

I am a bit confused though - when you compile `the_course.tex` what is the root file you'd want?

**Comment by ashthespy** [comment]
Closing this issue given the lack of response - feel free to comment to open it up again!
