### ISSUE TITLE
Use MacOS native preview for pdf viewer

### ISSUE THREAD

**Issue by Maxzhao1999** [James-Yu/Atom-LaTeX#161]
The PDF viewer bundled with Atom is slow and ugly on macOS, any chance you could provide an option to just use preview for opening pdfs in atom tab? Much like how TexShop does.
This is an enhancement suggestion. Thank you so much for this awesome package!

**Comment by ashthespy** [comment]
This would go against the [idea of the package](https://github.com/James-Yu/Atom-LaTeX#why-another-latex-package)
Sorry!
