### ISSUE TITLE
Multiple processes spawned.

### ISSUE THREAD

**Issue by SolidTux** [James-Yu/Atom-LaTeX#162]
If I save before the last build process is finished (with build on save enabled) another build process is spawn and this results in errors and corrupted temporary files.

**Comment by ashthespy** [comment]
@SolidTux that shouldn't happen. If you pop open the dev console - you should notice a cmd to kill the current running build when triggering a new build. Can you check if this (`Kill Compiler`) works as expected?

**Comment by SolidTux** [comment]
I get this error (sorry for it being in german)

```viewer.coffee:127 #of_pages is undefined.
viewer.coffee:127 #of_pages is undefined.
viewer.coffee:127 PDF 6277ca11b3820604cf482aa82a3d9519 [1.5 LuaTeX-1.7.0 / LaTeX with hyperref package] (PDF.js: 1.9.426 [WebGL])
builder.coffee:142 Error: Command failed: taskkill -pid 15828 /T /F
FEHLER: Der Prozess "15828" wurde nicht gefunden.



    at ChildProcess.exithandler (child_process.js:287)
    at emitTwo (events.js:126)
    at ChildProcess.emit (events.js:214)
    at maybeClose (internal/child_process.js:925)
    at Socket.stream.socket.on (internal/child_process.js:346)
    at emitOne (events.js:116)
    at Socket.emit (events.js:211)
    at Pipe._handle.close [as _onclose] (net.js:554)
builder.coffee:143 > taskkill -pid 15828 /T /F


builder.coffee:144 FEHLER: Der Prozess "15828" wurde nicht gefunden.

viewer.coffee:127 #of_pages is undefined.
viewer.coffee:127 #of_pages is undefined.
viewer.coffee:127 PDF 6277ca11b3820604cf482aa82a3d9519 [1.5 LuaTeX-1.7.0 / LaTeX with hyperref package] (PDF.js: 1.9.426 [WebGL])
```

`FEHLER: Der Prozess "15828" wurde nicht gefunden.` means somethink like `ERROR: The process "15828" was not found.`

**Comment by ashthespy** [comment]
@SolidTux 
I will have to look into this, it should be able to terminate the process - unless it's finished already throwing the `FEHLER: Der Prozess "xxx" wurde nicht gefunden.` error. 

I don't seem to be able to reproduce the issue on my machine, so if you are up for it - we could add some debugging lines to see where we are loosing the process. I will try improve the debugging output of the package in the coming weeks.

PS:  Ich verstehe ein wenig Deutsch, also keine Probleme!

**Comment by SolidTux** [comment]
`I don't seem to be able to reproduce the issue on my machine, so if you are up for it - we could add some debugging lines to see where we are loosing the process. I will try improve the debugging output of the package in the coming weeks.`

Yes, just let me know what I can do!

`PS: Ich verstehe ein wenig Deutsch, also keine Probleme!`

A great, that simplifies things. I didn't see this error under Linux and I don't know how to change the language of the logs under Windows (maybe setting the system language?).

**Comment by ashthespy** [comment]
@SolidTux  sorry, I have been travelling and haven't had much time. Were you able to figure things out yet?

**Comment by SolidTux** [comment]
No, sorry. I don't use Atom currently ...

**Comment by ashthespy** [comment]
Fair enough, good luck!
