### ISSUE TITLE
Undefined references are not not shown

### ISSUE THREAD

**Issue by madsmh** [James-Yu/Atom-LaTeX#164]
Atom-LaTeX does not show warnings about undefined citations - this is critical when writing a thesis or large document with citations.

**Comment by ashthespy** [comment]
@madsmh What toolchain are you using? 
I get the expected warning message "Citation 'xxx' on Page 'y' undefined" with `biber`

**Comment by ashthespy** [comment]
Feel free to comment to reopen this issue!
