### ISSUE TITLE
moving files breaks "go to Tex from PDF"

### ISSUE THREAD

**Issue by AlessioMansutti** [James-Yu/Atom-LaTeX#167]
After changing the position of some files, the tool still track the previous position.
Then (for example), if we use the shortcut to jump from a position on the PDF to the corresponding part of the source file, a new file is open, at the old location of the file.

**Comment by ashthespy** [comment]
Do you mean, if you have a `doc.tex` and a `doc.pdf` and if you rename `doc.tex` to `doc2.tex` and then jump from `doc.pdf` it opens a new `doc.pdf`?

**Comment by ashthespy** [comment]
Fell free to post a reply to open the issue again!
