### ISSUE TITLE
Pdf viewer does not preview newly compiled pdfs after the first one.

### ISSUE THREAD

**Issue by Dirivian** [James-Yu/Atom-LaTeX#168]
When the user complies and runs a Tex file, the pdf viewer previews the document as it should.

Now, when compiling a new Tex file without restarting Atom, the pdf viewer keeps previewing the old pdf instead of the new one.

**Comment by ashthespy** [comment]
How do you compile the new file? The pdf viewer previews the pdf file corresponding to the current [root file](https://github.com/James-Yu/Atom-LaTeX#setting-the-latex-root-file).

**Comment by ashthespy** [comment]
Either split your projects into separate atom "projects" or Use the "Build LaTeX from current editor" function of the package.

**Comment by Dirivian** [comment]
That works. Do you want to close this issue or I can document this somewhere.

**Comment by ashthespy** [comment]
Hmm, this is kinda how most TeX editors work - but if you think it needs an explicit note - go ahead and open a PR :-)
