### ISSUE TITLE
Autocomplete for references and citations

### ISSUE THREAD

**Issue by nuskorpios** [James-Yu/Atom-LaTeX#17]
[latexer](https://github.com/Focus/latexer) does a good job in autocompleting [references](https://raw.githubusercontent.com/Focus/latexer/master/screenshots/ref.gif) and citations. Atom-LaTeX also does a good job in "autocomplete" environments; is there any chances for Atom-LaTeX to have the autocomplete feature for references and citations?

**Comment by James-Yu** [comment]
The extension can provide all autocompletes. For citation, you need to include the `.bib` file. For references, only `\label{something}` will be hinted. If it does not work, please provide more details.
