### ISSUE TITLE
Editor crashes when I use "\\" too many times.

### ISSUE THREAD

**Issue by amrakov** [James-Yu/Atom-LaTeX#170]
I have only encountered this problem so far when editing and making LaTeX files, so I'm operating under the assumption that this package is the cause. When I have to make files with lots of \tabular tables, and I keep using "\\" to end a row, my editor will eventually end up crashing and then I need to reload it. I have experienced this happening at least twice when building big tables after typing at least three different rows. I restart Atom and my computer and try again, but then my editor continues to crash. I can still work with it, I just keep getting slowed down every time I have to reload the editor. It seems to be that the specific issue with me using "\\" a lot might be the drop-down suggestion window that drops from it. Any help is welcome, as otherwise I enjoy using the package on Atom!

**Comment by ashthespy** [comment]
@amrakov Feel free to add new information, closing the issue until then!
