### ISSUE TITLE
PDF not being opened after building

### ISSUE THREAD

**Issue by bermudaparty** [James-Yu/Atom-LaTeX#172]
I'm successfully able to build latex and create a pdf. But both settings to automatically open the pdf after building (in tab or in own window) don't work. Nothing happens.

How do I debug this?

**Comment by ashthespy** [comment]
First step would be to check if there are errors on the debug console (`ctrl`+`shift`+`i`) I'd recommend setting the Preview PDF to `View in PDF viewer tab` option for debugging.

**Comment by bermudaparty** [comment]
Thank you. In the console I have the following messages after freshly opening atom. No new messages show up when building latex (neither with open in window, or tab).

Note: I do not have admin rights on this computer. Mabye the Path error might be related to this?

```
<embedded>:120085
spell-check:en-us Cannot load the system dictionary for `en_US`. Checked the following paths for dictionary files:
* C:\
* C:\Users\sk18e721\AppData\Local\atom\app-1.29.0\resources\app.asar.unpacked\node_modules\spellchecker\vendor\hunspell_dictionaries

<embedded>:133161
Uncaught (in promise) Error: Path must be a valid path to a file or a directory.
    at C:\Users\sk18e721\AppData\Local\atom\app-1.29.0\resources\app\node_modules\@atom\nsfw\lib\src\index.js:97:17
    at tryCallOne (C:\Users\sk18e721\AppData\Local\atom\app-1.29.0\resources\app\node_modules\nodegit-promise\lib\core.js:37:18)
    at C:\Users\sk18e721\AppData\Local\atom\app-1.29.0\resources\app\node_modules\nodegit-promise\lib\core.js:103:21
    at flush (C:\Users\sk18e721\AppData\Local\atom\app-1.29.0\resources\app\node_modules\asap\raw.js:50:35)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ashthespy** [comment]
These don't look like errors from the package.
But, how come you don't have something like `manager.coffee:198 RootWatcher Init: 0.017333984375ms` as well?

Once the build is successful, can you try launching the viewer from  `Packages` -> `Atom-Latex` ->`Preview PDF in new tab`  (with the debugger open).
If that doesn't work still - can you type in `atom_latex.latex.viewer` into the debug console and let me know the response?

**Comment by bermudaparty** [comment]
> But, how come you don't have something like manager.coffee:198 RootWatcher Init: 0.017333984375ms as well?

I don't know.. ^^

> Once the build is successful, can you try launching the viewer from Packages -> Atom-Latex ->Preview PDF in new tab (with the debugger open).

Nothing happens. No tab opens, no new message in the console.

> If that doesn't work still - can you type in atom_latex.latex.viewer into the debug console and let me know the response?

So you mean: `ctrl + shift + i` -> `Console` -> `Filter` Textbox? The two messages I posted above are literally the only messages in the console. So filtering by `atom_latex.latex.viewer` turns up nothing.

Thank you for your help by the way!

**Comment by ashthespy** [comment]
>>But, how come you don't have something like manager.coffee:198 RootWatcher Init: 0.017333984375ms as well?
>
>I don't know.. ^^

Hmm,interesting. More questions:
How do you invoke the packages builder? 
What does it say in the LaTeX panel? (Click on the `Atom-LaTeX panel` -> `Show build log`)

>So you mean: ctrl + shift + i -> Console -> Filter Textbox? The two messages I posted above are literally the only messages in the console. So filtering by atom_latex.latex.viewer turns up nothing.

Nope, just `ctrl` + `shift` + `i` ->`Console` and type into the prompt (`>`) there

**Comment by bermudaparty** [comment]
> How do you invoke the packages builder?

I'm not sure what you mean by this. 

> What does it say in the LaTeX panel? (Click on the Atom-LaTeX panel -> Show build log)

I attached the log from the latest build. It's pretty long with a lot of warnings (that seem irrelevant to me). On another system I'm not having problems with the same project.
[tmp-7696lq9K07B0VOO5.txt](https://github.com/James-Yu/Atom-LaTeX/files/2323675/tmp-7696lq9K07B0VOO5.txt)


> Nope, just ctrl + shift + i ->Console and type into the prompt (>) there

Ah, I understand. I get this:

```
atom_latex.latex.viewer
Viewer {latex: AtomLaTeX, client: {…}}
client: {}
latex: AtomLaTeX {disposables: CompositeDisposable, builder: Builder, cleaner: Cleaner, manager: Manager, viewer: Viewer, …}
__proto__: Disposable
```

**Comment by ashthespy** [comment]
>> How do you invoke the packages builder?
>I'm not sure what you mean by this.

I.e Build from here vs `ctrl`+ `l` + `ctrl` + `b` vs ( you get the picture ;-))
>> What does it say in the LaTeX panel? (Click on the Atom-LaTeX panel -> Show build log)

I meant this log, not the `Show raw log` that you have attached. 
![image](https://user-images.githubusercontent.com/16233271/44658641-cf099100-aa01-11e8-847a-bc1882562e84.png)

> Ah, I understand. I get this:

Hmm, looks like the viewer hasn't been able to determine the path to the preview file. 
Which leads to the next question -- How do are you setting your [LaTeX root file](https://github.com/James-Yu/Atom-LaTeX#setting-the-latex-root-file)?

**Comment by bermudaparty** [comment]
> How do you invoke the packages builder?
> How do are you setting your LaTeX root file?

So I have a main file that combines content from several other files. Every file has a "magic" (?) comment at the top like so: `% !TEX root = ..\main.tex`

I build the file by clicking the play arrow ("Build Latex") in the Atom-Latex panel. Sometimes when in one of the sub-files, sometimes when in the root file. It makes no difference. I initially never manually set the root file.
But I did just try out if that would change something. But the behaviour is still the same, even after manually setting the root file.

> I meant this log, not the Show raw log that you have attached.

Ah, sorry. I thought that was just a condensed version of the raw log. Here it is:
![grafik](https://user-images.githubusercontent.com/17196288/44711914-cb344800-aaaf-11e8-8ee5-5bfa711ed5c3.png)

Maybe important: the same setup works on another computer. (The float too large warning is from a table being to big.)

**Comment by ashthespy** [comment]
Thanks for the feedback - would you be willing to jump in add a line to your code? 
I suspect that the package is unable to determine the path to the PDF. 
Can you navigate to Settings>Packages>Atom-LaTeX>View Code and then make this change in `lib/viewer.coffee`
```diff
index b838924..9fd9c26 100644
--- "a/.\\\lib\\viewer.coffee"
+++ "b/.\\lib\\viewer.coffee"
@@ -76,6 +76,7 @@ class Viewer extends Disposable
   openViewerNewWindow: ->
     pdfPath = @latex.manager.findPDF()
     if !fs.existsSync pdfPath
+      console.log """Unable to determine if #{pdfPath} exists"""
       return

     if !@getUrl()
@@ -99,6 +100,7 @@ class Viewer extends Disposable
     pdfPath = @latex.manager.findPDF()

     if !fs.existsSync pdfPath
+      console.log """Unable to determine if #{pdfPath} exists"""
       return

     if !@getUrl()
```
Reload Atom with `ctrl`+`shift`+`f5` and let me know if that throws a more meaningful error?

**Comment by bermudaparty** [comment]
Ah yes now we're getting somewhere. This gives `Unable to determine if \\nas-sowi.pdf exists`. 
That is not the correct file path.

The full path would be: `\\nas-sowi.campus.myuniversity.mycountry\sowi\homes\soz\myusername\Documents\myprojectfolder\main.pdf`

(myuniversity, myusername, etc. for anonymity. The original names are all just letters, no special characters, no spaces.)

This is at my workstation at university and it is some kind of setup where I can log in at any computer and always get access to all my files in the same way. I don't know what the technical terms for it are.

**Comment by ashthespy** [comment]
Ah - yes the [regex](https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/manager.coffee#L148) fails for this path. 
This should fix it!
``` diff
@@ -145,7 +145,7 @@ class Manager extends Disposable
     if !@findMain()
       return false
     # mainFile.blah.tex -> mainFile.pdf
-    return @latex.mainFile.replace(/\.([^\/]*)$/, '.pdf')
+    return @latex.mainFile.replace(/\.([^\\|\/]*)$/, '.pdf')
```

**Comment by bermudaparty** [comment]
Awesome, now it works. Thank you so much!

**Comment by ashthespy** [comment]
I will reopen it to remind me to push this fix to the next update :-)

**Comment by bermudaparty** [comment]
Ah, sure. I thought you might want that.. :-)
