### ISSUE TITLE
Object.basename is deprecated.

### ISSUE THREAD

**Issue by reskes** [James-Yu/Atom-LaTeX#173]
Arguments to `path.basename` must be strings
```
Object.basename (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:31:10)
Viewer.refresh (/Users/keskin/.atom/packages/atom-latex/lib/viewer.coffee:57:23)
Builder.postBuild (/Users/keskin/.atom/packages/atom-latex/lib/builder.coffee:163:27)
Builder.buildProcess (/Users/keskin/.atom/packages/atom-latex/lib/builder.coffee:68:14)
ChildProcess.<anonymous> (/Users/keskin/.atom/packages/atom-latex/lib/builder.coffee:109:19)
emitTwo (events.js:126:13)
```

**Comment by ashthespy** [comment]
Hi, can you open up the dev console (`ctrl` + `shift` + `f5`) and let me know the output of the following when you get this error?:
```js
> atom_latex.latex.mainFile
> atom_latex.latex.logger.debuglog.log
```
It would seem that there is some issue parsing the filename of the PDF.

**Comment by reskes** [comment]
sorry for my delay. didn't get the mail from GitHub regarding new comment.

yes it is a string, containing the path + "main.pdf", so it seems to be parsed correctly.

**Comment by ashthespy** [comment]
I will need more logs when this error is thrown. I.e `atom_latex.latex.manager.findPDF()`.  That is the only argument passed to `path.basename`. So I can't see how there is a non string argument 😟

**Comment by reskes** [comment]
I don't know how but the issue seem to be have solved itself.
My assumption is that it was in combination with an other third-party plugin

**Comment by oparisblue** [comment]
I got this error today:
![Issue](https://i.imgur.com/gfq91aA.png)

Some context: I deleted the latex file using my system explorer while it was still set as the main file in Atom-Latex; and then got the yellow deprecation message at the bottom of the screen.

**Comment by fportales** [comment]
> Best guess: `atom_latex.latex.manager.findPDF()` returns null if it can't file the file, and thus `path.basename` is passed a non-string argument.

I just had the same error, it happened when I was writing a file from scratch, saved before defining the `\begin{document}` and saw the deprecation message.

**Comment by oparisblue** [comment]
Yup, `atom_latex.latex.manager.findPDF()` returns `false` if the file is not saved / doesn't exist; which is not a string, and hence causes the deprecation warning.

I'm thinking the issue is [here](https://github.com/ashthespy/Atom-LaTeX/blob/master/lib/viewer.coffee#L40), but I could be mistaken.

@ashthespy Could we get this issue re-opened?

**Comment by oparisblue** [comment]
I've created a pull request which fixes this issue: https://github.com/ashthespy/Atom-LaTeX/pull/227
