### ISSUE TITLE
PDF not being opened after building 

### ISSUE THREAD

**Issue by novski** [James-Yu/Atom-LaTeX#175]
I run through #172 and can't determine why my pdf does not open. The two added lines: `console.log """Unable to determine if #{pdfPath} exists"""` to not pop up in console. The 'magnifing glas' icon does not show the pdf as well but if i click on the main.pdf file it opens in atom. setings are set to: view in tab.
Don't know how to go further here... any idea how to debug, where to start?

**Comment by ashthespy** [comment]
Hi, can you open up the dev console (`ctrl` + `shift` + `f5`) and let me know the output of the following when you get this error?:
```js
> atom_latex.latex.mainFile
>atom_latex.latex.manager.findPDF()
> atom_latex.latex.logger.debuglog.log
```

**Comment by novski** [comment]
nothing hapens. Im on mac. 
seams like you whant me to restart? found that as windows shortkey in atom forum. Im on a mac.
```
atom_latex.latex.mainFile
undefined
atom_latex.latex.manager.findPDF()
"/Users/novski/Desktop/latex-tmp/simple/main.pdf"
atom_latex.latex.logger.debuglog.log
(2) ["Atom-LaTeX debug log initiated at 22:46:49 ↵↵", "[22:47:14| Info] PDF path: /Users/novski/Desktop/latex-tmp/simple/main.pdf"]
0:"Atom-LaTeX debug log initiated at 22:46:49 ↵↵"
1:"[22:47:14| Info] PDF path: /Users/novski/Desktop/latex-tmp/simple/main.pdf"
length:2
__proto__:Array(0)
```
this is my file:
```
% !TEX root = /Users/novski/Desktop/latex-tmp/simple/main.tex
\documentclass[11pt]{article}
\title{Brief Article}
\author{The Author}
\begin{document}
\maketitle
%\section{}
%\subsection{}
\end{document}
```
if i run the build once after a restart of atom it shows this:
```
atom_latex.latex.mainFile
"/Users/novski/Desktop/latex-tmp/simple/main.tex"
atom_latex.latex.manager.findPDF()
"/Users/novski/Desktop/latex-tmp/simple/main.pdf"
atom_latex.latex.logger.debuglog.log
(3) ["Atom-LaTeX debug log initiated at 22:51:30 ↵↵", "[22:52:06| Info] PDF path: /Users/novski/Desktop/latex-tmp/simple/main.pdf", "[22:52:55| Info] PDF path: /Users/novski/Desktop/latex-tmp/simple/main.pdf"]
0:"Atom-LaTeX debug log initiated at 22:51:30 ↵↵"
1:"[22:52:06| Info] PDF path: /Users/novski/Desktop/latex-tmp/simple/main.pdf"
2:"[22:52:55| Info] PDF path: /Users/novski/Desktop/latex-tmp/simple/main.pdf"
length:3
__proto__:Array(0)
```
is that helpful?

**Comment by novski** [comment]
no nothing. With Preview PDF as well nothing in console.

**Comment by ashthespy** [comment]
More debugging - in the dev console - can you try launching it manually with:
```js
> atom_latex.latex.viewer.openViewerNewTab()
```

**Comment by ashthespy** [comment]
Are you sure the package is loaded and enabled? 
Can you give me more details of your setup - how your the package?
For example, `atom_latex.latex` should already give you a good idea of the packages status. 
![image](https://user-images.githubusercontent.com/16233271/45485087-9df5c400-b756-11e8-9532-73d0933de49a.png)

**Comment by novski** [comment]
seams quite similar:
<img width="1080" alt="bildschirmfoto 2018-09-13 um 19 13 56" src="https://user-images.githubusercontent.com/6088056/45504097-386efb00-b789-11e8-897f-2141413811b6.png">

**Comment by ashthespy** [comment]
Hmm, don't understand why you get `undefined` then - this gets stranger and stranger. 
If you get the above, you should be able to see something like by tabbing:
![image](https://user-images.githubusercontent.com/16233271/45507633-f21e9980-b792-11e8-91aa-73d34ca33085.png)

Do you have a non standard atom / package installation?

**Comment by ashthespy** [comment]
And when you hit `openViewerNewTab()` from that menu it still shows `undefined` ?? 
That would be extremely weird!

Also looking at your package list, I would disable the other LaTeX packages and enable them one by one to check if any of them are causing some interference. Like the [readme says](https://github.com/James-Yu/Atom-LaTeX#why-another-latex-package) a lot of features are integrated into this package natively.

**Comment by novski** [comment]
do i have to restart after disableling and before testing?

**Comment by ashthespy** [comment]
Just to confirm - as you said initially, you are sure the `pdf` file is compiled and viewable correct?  
I.e from your previous steps, `"/Users/novski/Desktop/latex-tmp/simple/main.pdf"` is a file that you can access and open fine? 
If you, please open `"/Users/novski/Desktop/latex-tmp/simple/main.tex"` and try the following again, and share:
```js
> atom_latex.latex.mainFile
> atom_latex.latex.manager.findPDF()
> atom_latex.latex.viewer.openViewerNewTab()
```
`openViewerNewTab()` will return `undefined` if it can't find the file.

**Comment by novski** [comment]
First i executed the 3 commands after opening the tex file without building it. 
Then i built it and executed all 3 commands again.
![bildschirmfoto 2018-09-13 um 23 47 07](https://user-images.githubusercontent.com/6088056/45517701-5b140a80-b7af-11e8-8ad4-27ebcbab9833.png)

**Comment by novski** [comment]
I already reinstalled twice once even after deleting the ~.atom folder. 
All the not default packages exept atom-latex and packages-list 
![bildschirmfoto 2018-09-13 um 23 51 45](https://user-images.githubusercontent.com/6088056/45517930-0fae2c00-b7b0-11e8-95a8-1d7cfd69e84a.png)
are gone now.

**Comment by ashthespy** [comment]
Hmm, with your above example, what is the output of:
```js
> atom_latex.latex.manager.findPDF()
> require('fs').existsSync(atom_latex.latex.manager.findPDF())
```

**Comment by novski** [comment]
![bildschirmfoto 2018-09-14 um 00 04 22](https://user-images.githubusercontent.com/6088056/45518424-c363eb80-b7b1-11e8-904e-d2bf6f808bc5.png)

**Comment by ashthespy** [comment]
I am sorry that this is being so much effort. 😟 😖  
```js
> atom_latex.latex.viewer.getUrl()
> atom_latex.latex.viewer.url
```
That should give you a url like `http://127.0.0.1:63382/viewer.html?file=preview.pdf` that you can also open in a browser window. Do let me know what happens!

**Comment by novski** [comment]
i initialized a git repo to unclutter the pan.
![bildschirmfoto 2018-09-14 um 00 12 04](https://user-images.githubusercontent.com/6088056/45518736-d4f9c300-b7b2-11e8-9ccc-540780b2b12a.png)

**Comment by ashthespy** [comment]
Finally - we see the actual error! :-)
```js
> atom_latex.latex.server.http.address()
> atom_latex.latex.server
```

**Comment by novski** [comment]
![bildschirmfoto 2018-09-14 um 00 18 19](https://user-images.githubusercontent.com/6088056/45518995-b3e5a200-b7b3-11e8-84d8-4c4724271126.png)

**Comment by ashthespy** [comment]
I have never seen this before. 
Can you try the same set of commands again after refreshing atom? (`cmd` + `shift` + `f5`).
Build latex and they try opening new tab,
```js
> atom_latex.latex.server.http.address()
> atom_latex.latex.server
```
if you still get null, then it is going to be hunting time ;-)

**Comment by novski** [comment]
i did not find a key binding that coresponds to (cmd + shift + f5) but i found a package that does a restart. I did that. It realy closes Atom and restarts as if i wold quit and click the icon again, even the dot beside the icon goes away for a second. But still i get the same as above.

**Comment by novski** [comment]
if you pm me at @novski over telegram tomorrow i can let you on my system. If that helps... im located in Switzerland. UTC+2. Maybe around 5PM or later wold be good..

**Comment by ashthespy** [comment]
Sorry I didn't catch this earlier (doing multiple things + it's quite late here as well!), but your error is clearly visible in your screenshot:
```
Error: getaddrinfo ENOTFOUND localhost
```
Looks like you might have a messed up `hosts` file. 
```sh
cat /etc/hosts
```
should have this entry:
```
 127.0.0.1 localhost
```
http://osxdaily.com/2014/04/12/restore-original-hosts-file-mac/

**Comment by novski** [comment]
yep that was it!
![bildschirmfoto 2018-09-14 um 00 49 08](https://user-images.githubusercontent.com/6088056/45520076-045efe80-b7b8-11e8-85d9-c44f754b7ffe.png)

Thanks a lot!

**Comment by ashthespy** [comment]
No issues, sorry for not spotting it earlier!
