### ISSUE TITLE
tex files open with text.tex.latex.beamer grammar

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#176]
Just noticed that spell check stopped working. I took a look why and noticed that tex files intended for inclusion (i.e. without `\documentclass`) are opened with text.tex.latex.beamer grammar by default.

Don't know why exactly beamer documents have their own grammar at all, but maybe this isn't intended behavior?! If it is, then maybe add to the relevant section in README that text.tex.latex.beamer is also a reasonable grammar when enabling spell check for LaTeX.

**Comment by ashthespy** [comment]
Sorry, this is an artefact of https://github.com/James-Yu/Atom-LaTeX/commit/788796b8985e27ad5e3985c722e009253cb496db 
There are some workaround on how to fix it, but if nothing comes up, shall revert that commit for now.

**Comment by Aerijo** [comment]
@ashthespy So I think it was you on Slack... anyway, I've [made a PR](https://github.com/atom/first-mate/pull/109) to first-mate that should give a way to resolve the issue. I don't know if it will get accepted (stability seems very important to nowadays), but it seems harmless enough.

**Comment by ashthespy** [comment]
@Aerijo Indeed was me, thanks!

**Comment by lsfinn** [comment]
I note that "Latex Memoir.cson" grammar is also missing fileTypes "tex". 
Would it be reasonable to add a contentRegex along the lines of "^%[ ]*-\\*-[ ]*[bB]eamer[ ]*-\\*-" to "Latex Memoir.cson", (mutatis mutants "Latex Beamer.cson") so that a comment of the form 
% -*- memoir -*- 
would select the desired grammar (or, if absent entirely, fall-back to the latex grammar)?

I've been trying to make this work; however, I'm not sufficiently adept at all the escaping needed to correctly specify the regular expression .

**Comment by HDembinski** [comment]
I am also here for this bug. I am new atom user, and this was really confusing and almost turned me away.

**Comment by ashthespy** [comment]
@lsfinn `contentRegex` needs https://github.com/atom/first-mate/pull/109 to be merged for it work, hopefully it gets merged soon!

**Comment by gwylanscheeren** [comment]
> 
> 
> Sorry, this is an artefact of [788796b](https://github.com/James-Yu/Atom-LaTeX/commit/788796b8985e27ad5e3985c722e009253cb496db)
> There are some workaround on how to fix it, but if nothing comes up, shall revert that commit for now.

Is there any progress on this? Is there indeed a workaround you suggest to use in the meantime?

**Comment by JackSwett** [comment]
Hey guys, this was fixed right away when I moved `\documentclass` to the top of the `.tex` file. For me, I'm using the IEEE template you can find online and it has comments before the `\documentclass`, which was messing with how the grammar was being categorized. 

I know its not a great fix, but its a decent workaround. If not, just add `text.tex.latex.beamer` to your grammar.

**Comment by shadyaristotelessnail** [comment]
With the package file-types you can set up that all .tex files are in text.tex.latex grammar .
For me, who is only use latex and no latex.beamer, this is perfect.
[https://atom.io/packages/file-types](file-types)

My config looks like this and works fine:
`core:
"file-types":
    "*.tex": "text.tex.latex"`

I personally think this is an easy and pleasant workaround.

**Comment by ashthespy** [comment]
Should be fixed with d53027c50a5daf618ee3999fad6f27003e3ae105 that lands in `v0.8.6`
