### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Google Drive/6. Teaching/Econ 3102 - I...

### ISSUE THREAD

**Issue by jaitx001** [James-Yu/Atom-LaTeX#177]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/estebanjait/Google Drive/6. Teaching/Econ 3102 - Intermediate Macro/FALL 2018/Notes

**Comment by ashthespy** [comment]
#108
