### ISSUE TITLE
Failed Building LaTeX (code ENOENT).

### ISSUE THREAD

**Issue by TheLastDestroyer** [James-Yu/Atom-LaTeX#178]
Installed full texlive from mint software center and am able to build documents fine in the terminal, however building in atom (either automatically on save or through the packages menu) throws:
**Failed Building LaTeX (code ENOENT).**
spawn /usr/bin/pdflatex ENOENT

with build log:
> /usr/bin/pdflatex -synctex=1 -interaction=nonstopmode -file-line-error test

running the same command in the terminal (literally copy paste from the log) from the same directory with my document (test.tex) works fine. had a look through https://github.com/James-Yu/Atom-LaTeX/issues/99 but dont think I've got the same problem they had as this is just a single file.

running a desktop linux mint 19 64 bit, atom 1.31.2, atom-latex 0.0.5

**Comment by ashthespy** [comment]
@TheLastDestroyer Can you open up the dev console (`ctrl`+`shift`+`i`) and check the outputs of the following:
```
> atom_latex.latex.mainFile
```

**Comment by TheLastDestroyer** [comment]
undefined
![image](https://user-images.githubusercontent.com/17359435/47152063-7a80e480-d2d3-11e8-9e05-72e10b276d62.png)

**Comment by ashthespy** [comment]
Sorry, please try it after invoking a build - it will be `undefined` now as it's not yet been set.

**Comment by TheLastDestroyer** [comment]
sorry, now its "/home/<user>/Documents/test/test.tex"
which is where my file is

**Comment by ashthespy** [comment]
Interesting the double `//`  wonder if that is leading to the `ENOENT` errors from spawn.

Could you check if the following command works fine? 
```
cwd = require("path").dirname(atom_latex.latex.mainFile)
require("child_process").execSync("pdflatex --version",{cdw:cwd}).toString()
```

**Comment by TheLastDestroyer** [comment]
dubbel // is just where my username is, markdown hid what i put there

**Comment by TheLastDestroyer** [comment]
first command works fine, printing the directory with my file in, second one fails with:

Uncaught Error: Command failed: pdflatex --version              child_process.js:656
/bin/sh: pdflatex: command not found


    at checkExecSyncError (child_process.js:613)
    at Object.execSync (child_process.js:653)
    at Object.execSync (ELECTRON_ASAR.js:728)
    at <anonymous>:1:26

**Comment by ashthespy** [comment]
Um, how come it can't find it?  Has it not been added to your path?

```
>atom_latex.latex.builder.binCheck('pdflatex')
>atom_latex.latex.builder.setCmds()
>atom_latex.latex.builder.cmds
```

**Comment by TheLastDestroyer** [comment]
rather a lot of output so I've put it in a [gist](https://gist.github.com/TheLastDestroyer/00d36c17d034708974a7149499ab51a3)

**Comment by TheLastDestroyer** [comment]
also might be relevant `require("child_process").execSync("pwd",{cdw:cwd}).toString()`  prints my home directory "/home/USER" not the directory for atom_latex.latex.mainFile

**Comment by ashthespy** [comment]
A. There was a typo in my snippet - it should be `cwd` no `cdw`
B. child_process

> 
> 
> also might be relevant:
> 
> ```
> cwd = require("path").dirname(atom_latex.latex.mainFile)
> require("child_process").execSync("pwd",{cdw:cwd}).toString()
> ```
> 
> prints my home directory `/home/USER` not the directory for atom_latex.latex.mainFile
There was a typo in my snippet - it should be `cwd` no `cdw`

> also running `require("child_process").execSync("ls /usr/bin/pdflatex",{cdw:"/home/max/Documents/test"}).toString()` in atom dev terminal returns a no such file error while running the same in terminal (running through node and running `ls` directly in bash) shows pdflatex as expected

Is there a reason why TeXLive didn't add these binaries to your PATH?

**Comment by TheLastDestroyer** [comment]
they are in my path in the terminal, its only when running through the atom dev shell they seem to be missing

**Comment by TheLastDestroyer** [comment]
![image](https://user-images.githubusercontent.com/17359435/47174769-77a0e680-d309-11e8-808b-6016decdc465.png)

**Comment by TheLastDestroyer** [comment]
fixed it (somehow) uninstalled the mint package manager version of atom and installed the deb directly from the website, suddenly everything works fine, seems it was being sandboxed by mint installing it as a flatpack or something

**Comment by isaacjoy** [comment]
Also running into this problem

**Comment by TheLastDestroyer** [comment]
> Also running into this problem

Make sure you've installed the version of atom from the atom website (and not the flatlak version if there is one) the software center version is sandboxes so cant access the required files

**Comment by isaacjoy** [comment]
Thanks @TheLastDestroyer, working now!

**Comment by Alex-Linhares** [comment]
Solved it for me; Thanks very much!
