### ISSUE TITLE
Setting environment variables

### ISSUE THREAD

**Issue by BeastyBlacksmith** [James-Yu/Atom-LaTeX#180]
Would be nice to be able to set environment variables such as `TEXINPUTS` in the settings. So custom paths can be searched for packages of `.sty` files.
Or is there already an undocumented way to do this?

**Comment by ashthespy** [comment]
Hi, no there is not current functionality for this - a workaround would be to set up a script to do this and then add a custom command into the custom toolchain. So something along the lines of:
```
set_paths.sh && latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf
```
