### ISSUE TITLE
Incompatible native module

### ISSUE THREAD

**Issue by louisld** [James-Yu/Atom-LaTeX#182]
Hello,
when I try to install the package in atom I get the following error :
`Failed to require the main module of 'latex' because it requires one or more incompatible native modules (build). Run apm rebuild in the package directory and restart Atom to resolve.`
I tried `apm rebuild` but it doesn't change anything. It doesn't say which module is problematic.
I tried to reinstall atom but nothing changed.
The version of atom is 1.32.0 x64. I'm running on ArchLinux so I installed it via pacman. I installed atom-latex via settings tab in atom. The version of atom-latex is 0.8.5. I also installed language-latex 1.2.0.

**Comment by ashthespy** [comment]
Hmm, not sure - but your best bet would be to remove the `node_modules` folder under the package (` ~/.atom/packages/`) and run `apm rebuild` again.

**Comment by louisld** [comment]
I don't know why but it finally works. I didn't do `apm rebuild` nor removing the `nodes_modules` folder. I will reopen the issue if I get the same error.
