### ISSUE TITLE
build with make file in main path possible?

### ISSUE THREAD

**Issue by novski** [James-Yu/Atom-LaTeX#185]
I usaly build by executeing my own makefile that is in the main path as a separate file called "makefile" it does some special things like converting my svg images automaticaly to pdf and such things so it's not possible to do that with the custom toolchain and defining a latexmk -pdf <file> command or so.
I wold like to know if its possible to execute that makefile somehow with Atom-LaTeX?
Regards, Novski

**Comment by ashthespy** [comment]
It would be the same way you set up a [custom toolchain](https://github.com/James-Yu/Atom-LaTeX#-setting-up-a-toolchain).
You could either set it up per project with a [`.latexcgf`](https://github.com/James-Yu/Atom-LaTeX#latexcfg) or globally.
