### ISSUE TITLE
preview tab hangs

### ISSUE THREAD

**Issue by rolandg** [James-Yu/Atom-LaTeX#188]
Hello and thanks for your great work.
I have the following issue:
While using the plugin with the pdf preview tab open after some time the preview tab starts to hang.
I cannot scroll or click anything in the tab anymore. The only thing to solve is to close and reopen the preview.

I could not find out what triggers the problem. 
Here is my debug console output:
```
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.    viewer.coffee? [sm]:127 
%cElectron Security Warning (Insecure Resources)    viewer.coffee? [sm]:127
%cElectron Security Warning (Insecure Content-Security-Policy)    viewer.coffee? [sm]:127 
PDF 17503e33dc85d95f3d2ba932509de6db [1.5 pdfTeX-1.40.19 / LaTeX with hyperref] (PDF.js: 1.9.426 [WebGL])    viewer.coffee? [sm]:127 
```
This is before it hangs. Doesn't output anything when it gets stuck.
Thanks

**Comment by rolandg** [comment]
Yes it does. Tested it with a minimal document. 
It takes around 2 minutes after opening the tab to freeze.
Seems like it doesn't matter what I do. Freezes if I leave it alone or during scrolling.

Tried to make a command to close the tab and reopen with a shortcut but my coffee script / atom skills are too limited.

**Comment by ashthespy** [comment]
Glad you found a workaround. Does this hanging issue persist in a new window as well?
Unfortunately, there is not much I can do to help you debug - it most likely a platform/installation specific issue as you seem to be the only one affected by this.

**Comment by jlbosse** [comment]
I can confirm this bug. Regardless of the document size, the PDF preview tab hangs after about 2 minutes and the only way to get it to work is closing it and hitting C-l C-b again. It happens on both my Manjaro 17 and Manjaro 18 installation as well as under Arch Linux.

**Comment by ashthespy** [comment]
Closing this in favour of #204 which has more logs..
