### ISSUE TITLE
Change background  color of PDF viewer?

### ISSUE THREAD

**Issue by dpo** [James-Yu/Atom-LaTeX#192]
In the interest of saving my eyesight and also a little energy, I've been trying to change the background color of the PDF viewer window from white to a light gray. (I managed to do this in the past in the Skim PDF viewer and it's been a godsend.) So far, I haven't been successful. I tried changing https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/viewer.coffee#L89 to something of the form
```coffee
@window = new BrowserWindow(backgroundColor: '#D3D3D3')
```
following [the documentation](https://electronjs.org/docs/api/browser-window#setting-backgroundcolor). However, what happens is that the background is light gray when the viewer window pops up but changes to white after a brief moment.

I've tried changing colors in https://github.com/James-Yu/Atom-LaTeX/blob/master/viewer/viewer.css with no luck.

I did find this bug report: https://github.com/electron/electron/issues/12211. Is that what is at work here, or is there another way to change the background color that I missed?

Thanks in advance!

**Comment by dpo** [comment]
Temporary workaround:
```tex
\usepackage{xcolor}
\pagecolor[rgb]{0.7,0.7,0.7}
```
but it would be best if I didn't have to remember to change the background to white before printing or e-mailing my PDF.

**Comment by dpo** [comment]
ps: I tried not loading the `viewer.css` stylesheet in `viewer.html`, but the background still changes to white after a short moment.

**Comment by ashthespy** [comment]
@dpo  Give me a few days - I need to sync up some local changes and bump up `pdfjs` to make these things easier!

**Comment by dpo** [comment]
@ashthespy No rush. Many thanks for looking into this!

**Comment by ashthespy** [comment]
@dpo 
I had a quick look at this now, it doesn't seem to be to easy (https://github.com/mozilla/pdf.js/issues/2163)
That being said, as it's just CSS and after spending some time trying to see how to get `invert()` working, had the epiphany to look at LaTeX-Workshop and so after ~borrowing~ stealing some more stuff:

```diff
commit f1394aeb1e2ec8f869f417c669c121a5d3f1cc03
Author: ashthespy <ashthespy@gmail.com>
Commit: ashthespy <ashthespy@gmail.com>

    Add a 'dark mode' via `invert_viewer` option

diff --git a/lib/viewer.coffee b/lib/viewer.coffee
index b838924..e8d0e42 100644
--- a/lib/viewer.coffee
+++ b/lib/viewer.coffee
@@ -23,6 +23,10 @@ class Viewer extends Disposable
       when 'loaded'
         if @client.position and @client.ws?
           @client.ws.send JSON.stringify @client.position
+        @client.ws.send JSON.stringify {
+                            type: 'params',
+                            invert: atom.config.get('atom-latex.invert_viewer'),
+                            }
       when 'position'
         @client.position = data
       when 'click'
diff --git a/viewer/latex.css b/viewer/latex.css
index 41f682b..8d446c1 100644
--- a/viewer/latex.css
+++ b/viewer/latex.css
@@ -21,3 +21,9 @@
     height: 128px;
     width: 128px;
 }
+
+/*  page border remains visible on inversion */
+.pdfViewer.removePageBorders .page {
+    border: none;
+    box-shadow: 0px 0px 0px 1px lightgrey;
+}
diff --git a/viewer/latex.js b/viewer/latex.js
index ab91d30..4f6fc72 100644
--- a/viewer/latex.js
+++ b/viewer/latex.js
@@ -51,6 +51,13 @@ socket.addEventListener("message", (event) => {
             document.getElementById('viewerContainer').scrollTop = data.scrollTop;
             document.getElementById('viewerContainer').scrollLeft = data.scrollLeft;
             break;
+        case "params":
+            if (data.invert > 0) {
+              document.querySelector('#viewer').style.filter = `invert(${data.invert * 100}%)`
+              document.querySelector('#viewer').style.background = 'white'
+            }
+            break;
         default:
             break;
     }
```

Was a bit impatient and pushed the new update, so this should land in the next one, after I find some time to address the other issues.

**Comment by dpo** [comment]
Many thanks @ashthespy ! I'll give it a go!

**Comment by ashthespy** [comment]
@dpo published with `atom-latex@v0.8.7`
The documentation is quite sparse at the moment - but in a gist:
A new `invert_viewer` key can be added to `config.cson` under `atom-latex`. The value (0.0-1.0) value is used to run a [CSS invert](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert) on the background styles.  Additionally, you can toggle this invert mode from the viewer with <kbd>ctrl</kbd><kbd>i</kdb>

**Comment by dpo** [comment]
@ashthespy Thank you so much!!! This is one of the top features of your viewer! I agree that the dark mode looks good, but a low value such as `invert_viewer = 0.05` is already so much easier on the eyes!!!

**Comment by Elijahh177** [comment]
I'm afraid this option doesn't work for me.
`atom@1.39.1`
`atom-latex@0.8.8`

When I add the option `invert_viewer: 0.05` in `config.cson` under `atom-latex`, atom won't start anymore...

**Comment by ashthespy** [comment]
Looks like you might have a syntax issue - what does you `config.cson` look like?

**Comment by Elijahh177** [comment]
```
"atom-latex":
    bibtex: "biber"
    build_after_save: false
    clean_after_build: true
    combine_typesetting_log: false
    focus_viewer: true
    hide_log_if_success: true
    preview_after_build: "View in PDF viewer tab"
    save_on_build: true
    toolchain: "custom toolchain"
    invert_viewer: 0.05
```

**Comment by ashthespy** [comment]
@Elijahh177  I don't see anything amiss there - but atom not starting would imply something wrong with your entire `config.cson` file, not just the entry for `atom-latex`.

**Comment by Elijahh177** [comment]
I didn't changed any other part of `config.cson`...
When removing the `invert_viewer` line, atom starts normally

**Comment by ashthespy** [comment]
@Elijahh177 There should be no reason for atom not to start - care to share your full `config.cson`? 
You might have issues with your syntax when you added the new key. Try adding it right under the `"atom-latex":` key to rule that out.

**Comment by Elijahh177** [comment]
Tryed your suggestion too, same behavior...
Here's my full `config.cson`:

```
"*":
  "atom-latex":
    bibtex: "biber"
    build_after_save: false
    clean_after_build: true
    combine_typesetting_log: false
    focus_viewer: true
    hide_log_if_success: true
    preview_after_build: "View in PDF viewer tab"
    save_on_build: true
    toolchain: "custom toolchain"
  core:
    allowPendingPaneItems: false
    disabledPackages: [
      "wrap-guide"
    ]
    ignoredNames: [
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "._*"
      "Thumbs.db"
      "desktop.ini"
      ".pioenvs"
      ".piolibdeps"
      ".clang_complete"
      ".gcc-flags.json"
    ]
    telemetryConsent: "no"
    themes: [
      "one-dark-ui"
      "base16-tomorrow-dark-theme"
    ]
    uriHandlerRegistration: "always"
  editor:
    fontSize: 16
    softWrap: true
  "exception-reporting":
    userId: "4ec21221-fbbd-c20c-b1a1-bc570e9b52a0"
  "file-icons":
    coloured: false
  latextools:
    viewer: "pdf-view"
    win32:
      distro: "texlive"
  "linter-ui-default":
    useBusySignal: false
  "spell-check":
    addKnownWords: true
    grammars: [
      "source.asciidoc"
      "source.gfm"
      "text.git-commit"
      "text.plain"
      "text.plain.null-grammar"
      "text.tex.latex"
    ]
    knownWords: [
      "Transimpedanzverstärker"
      "Lissajous"
      "includegraphics"
      "textwidth"
    ]
    locales: [
      "de-DE"
      "en-US"
    ]
  "tool-bar":
    position: "Left"
  "tree-view":
    hideIgnoredNames: true
  welcome:
    showOnStartup: false
".bibtex.text":
  editor:
    showInvisibles: false
```

**Comment by ashthespy** [comment]
I don't see any issues again - your config works fine on my test installation (I don't have all your packages installed however)
Unfortunately, your best bet at this point is trial and error to figure out what is causing your issue..

**Comment by Elijahh177** [comment]
The odd part is, that the "auto hide" function of the pdf viewer menubar does not work properly, too. The menubar hides, but the grey background of the bar is still there. I have the problem on both of my Win10 machines.

I already deinstalled atom, deleted the whole `.atom` folder and installed only atom + `atom-latex`, but it didn't help.

**Comment by ashthespy** [comment]
>The odd part is, that the "auto hide" function of the pdf viewer menubar does not work properly, too. The menubar hides, but the grey background of the bar is still there. I have the problem on both of my Win10 machines.

That is all the current implementation does.. 

I am not sure why/what is happening in your case - is there anyway to log what is stopping atom from starting?

**Comment by dpo** [comment]
Coming back to this, I find that setting `invert_viewer` in `config.cson` interferes with setting the zoom level of the PDF viewer. I'm not setting any other option of `atom-latex` in `config.cson`. 

When I don't set *any* `atom-latex` option in `config.cson`, I like to set the zoom level to "page fit", adjust the window size so exactly one PDF page fits in the window, and "scroll" with the up and down arrow keys.

However, when I set `invert_viewer` in `config.cson`, that does't work any more. The arrow keys no longer work to change page.

Is anyone else able to reproduce this?

**Comment by dpo** [comment]
Today I discovered that setting `invert_viewer` also prevents me from clicking on links in the PDF...

**Comment by ashthespy** [comment]
@dpo Sorry, been on vacation, will have a look ASAP, and push some changes from my local branch.
