### ISSUE TITLE
key binding for preview pdf in tab

### ISSUE THREAD

**Issue by archimondain** [James-Yu/Atom-LaTeX#193]
I don't know if it is suppose to be like this : when I preview my pdf in a tab, it seems that the tab don't receive key events, like pageup, pagedown, moveup, movedown. It works fine on the tex tabs, or in the pdf viewer when it is on a separated window.

Is this normal ?

**Comment by ashthespy** [comment]
You are indeed right, I will have to take a look at this when I find some time.

**Comment by ashthespy** [comment]
@archimondain This was an electron/chrome issue with webviews, and seems to have been fixed now with Atom 1.39 (which uses Electron 3.x).
