### ISSUE TITLE
shell escape option?

### ISSUE THREAD

**Issue by dpo** [James-Yu/Atom-LaTeX#194]
I can't find the appropriate way to tell `latexmk` to call `pdflatex` with `-shell-escape`. Is it necessary to set up a custom toolchain? Thanks!

**Comment by ashthespy** [comment]
Best practice - yes. 
Easy option, edit the `latexmk` execution parameters in the package settings and add the flag.

**Comment by dpo** [comment]
Sorry for the basic question but I'm not having success with the custom toolchain. `-shell-escape` is an option of `pdflatex`, not of `latexmk`.
I set
* Custom toolchain commands to `%TEX %ARG %DOC`
* Latex compiler to use to `latexmk`
* Latex compiler execution parameters to `-synctex=1 -interaction=nonstopmode -file-line-error -e '$latex=q/pdflatex %O -shell-escape %S/'`

but a build fails immediately and the build command is all that's in the log.

What am I doing wrong?

**Comment by ashthespy** [comment]
Shouldn't it work just with `-synctex=1 -interaction=nonstopmode -file-line-error -shell-escape -pdf`? Not near my machine to test..

**Comment by dpo** [comment]
Hm. It does work. Pretty sure I tried it before but who knows. Thanks!
