### ISSUE TITLE
pdf not updating in pdf viewer

### ISSUE THREAD

**Issue by AshtonSBradley** [James-Yu/Atom-LaTeX#195]
I don't know if this is an issue for Atom-LaTeX  or PDF-View but the pdf that gets displayed seems to get out of sync with the document being latexed. If I latex a second document in the same session, then it refreshes the pdf displayed for the first document. This makes it basically unusable... is there something I am missing in settings, or is this a real issue?

**Comment by ashthespy** [comment]
@AshtonSBradley  How do you set your [LaTeX root file](https://github.com/James-Yu/Atom-LaTeX#setting-the-latex-root-file)? If the plugin doesn't have help figuring out what is the root file for the second document, then it will revert to displaying the pdf for the last root file that was determined/set.

**Comment by AshtonSBradley** [comment]
how do I tell it to always use the current document being built as the root file? 

There doesn't seem to be a mention of "root" in the settings for either pdf-view or atom-latex...

**Comment by AshtonSBradley** [comment]
when I try to `ctrl-l ctrl-h` to switch build files, I hit
https://github.com/James-Yu/Atom-LaTeX/issues/191

**Comment by ashthespy** [comment]
@AshtonSBradley Could you please then fill in the steps to reproduce the error (along with system info) to help debug that error. I can't seem to reproduce it here on my side..
