### ISSUE TITLE
Save files before Build make Build crash

### ISSUE THREAD

**Issue by baptistecottierperso** [James-Yu/Atom-LaTeX#198]
Hi, 
When I choose "Save files before Build", it generates this error. But no problem when saving on my own, then building. 

Here is the issue report :

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.5

### Stack Trace

Uncaught TypeError: Array.prototype.indexOf called on null or undefined

```
At /home/baptiste/.atom/packages/atom-latex/lib/builder.coffee:37

TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (<anonymous>)
    at Builder.module.exports.Builder.saveonBuild (/packages/atom-latex/lib/builder.coffee:37:34)
    at Builder.module.exports.Builder.build (/packages/atom-latex/lib/builder.coffee:19:18)
    at HTMLElement.click (/packages/atom-latex/lib/view/panel.js:111:85)
```

### Commands

```
     -4:45.2.0 atom-latex:build (input.hidden-input)
     -2:13.9.0 application:open-file (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
atom-latex 0.8.5 
latex-autocomplete 1.1.1 
platformio-ide-terminal 2.9.1 
```

**Comment by ashthespy** [comment]
Some questions:
1. Do you explicitly set the [LaTeX root file](https://github.com/James-Yu/Atom-LaTeX#setting-the-latex-root-file) if not, how is it determined? 
2. Could you try debugging by instead of clicking build the, opening up the dev console and running the following: 
```js
> atom_latex.latex.texFiles
// which should output something like
< undefined
// Then try
> atom_latex.latex.manager.findAll()
> atom_latex.latex.texFiles
```

**Comment by ashthespy** [comment]
Closing for now, feel free to comment here when you have more info to share!
