### ISSUE TITLE
LaTeX build process spawned. PID: undefined.

### ISSUE THREAD

**Issue by mlmayo** [James-Yu/Atom-LaTeX#199]
Some other folks seem to have this issue, but I'm on a Windows PC with MikTeX installation.  I installed the Latex-Workshop extension to vscode, but it doesn't appear to work.  I suspect the latex-workshop extension isn't pointed to my MikTeX installation, but can't seem to find how to specify its location.

I get 3 errors in OUTPUT when I try to compile a *.tex document with latex-workshop:

[11:24:03] LaTeX build process spawned. PID: undefined.
[11:24:03] LaTeX fatal error: spawn pdflatex ENOENT, . PID: undefined.
[11:24:03] Does the executable exist? PATH: 

Is there a way to point latex-workshop to my MikTeX installation?

**Comment by ashthespy** [comment]
Wrong issue tracker, this is for Atom, good luck!
