### ISSUE TITLE
No recognition of labels

### ISSUE THREAD

**Issue by johschmitz** [James-Yu/Atom-LaTeX#2]
When typing \ref a list of possible labels should be displayed to choose from.

**Comment by James-Yu** [comment]
Can you please provide more information on the issue? For example, a minimal tex file provided in gist and/or your LaTeX project folder structure. Thanks.

**Comment by johschmitz** [comment]
See for example the plugin https://github.com/Focus/latexer to understand what I mean.
Basically you have to search all `.tex` files and `.bib` files for references and provide some kind of list when the ref, cite and similar commands are typed.

**Comment by James-Yu** [comment]
That is what we do right now. Closed until further information.

**Comment by James-Yu** [comment]
New version `0.4.1` published which enhances the main file detection and logging. Please suggest any issue if the autocompletion still won't work with proper main file settings.
