### ISSUE TITLE
Preview pane closes automatically

### ISSUE THREAD

**Issue by bmrs** [James-Yu/Atom-LaTeX#200]
Hi,

After building with Atom-LaTeX, preview opens up with the built file but automatically closes shortly after. The PDF has no trouble, but it also occurs when trying to preview the file (cmd-l + cmd-p). Thanks for your help.

**Comment by ashthespy** [comment]
Could you share more debugging info I could use to try and recreate this?
1. Tab or Window viewer?
2. Any information in the debug console? (<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>)

**Comment by bmrs** [comment]
It was with the window. After a system restart, the bug disappeared and nothing shown on the debug console… Thanks anyway.
