### ISSUE TITLE
Highlight line on reverse SyncTeX (Enhancement Request)

### ISSUE THREAD

**Issue by JackSwett** [James-Yu/Atom-LaTeX#201]
First off, thank you for working on this package! Works great!

I was wondering if you could add an option to the settings, that when enabled, would highlight the line in the editor window that was clicked in the pdf window. Currently, when using SyncTeX, the cursor just moves to the start of the line, but I (and I assume some other people) have trouble seeing the cursor quickly. 

I would LOVE for a setting that would select (and therefore highlight) the entire line when using SyncTex.

**Comment by ashthespy** [comment]
Finally got some time to give this package the love it deserves. 
Have implemented a simple box highlight for PDF > editor,  
and a marker (stolen from this package's VS code counterpart) for editor > PDF
Should be in `v0.8.6` of the package.
