### ISSUE TITLE
spawn myfile ENOENT

### ISSUE THREAD

**Issue by Fredastair** [James-Yu/Atom-LaTeX#202]
Hello there,

I'm trying to use atom with latex, so I wanted to try the atom-latex package. But an error message keeps popping : 

Failed Building LaTeX (code ENOENT).
spawn empty ENOENT

Where empty.tex is my file containing : 

\documentclass[11pt]{article}
\begin{document}
  coucou 
\end{document}

of course I've checked on TeXmaker and it's compiled fine... 

Detail:
I am running on Windows 10.

Thanks in advance.

**Comment by blauertee** [comment]
How did you install Atom? I had this issue as well because i had installed it as flatpak that causes issues with file access. Since I installed the system wide .deb everything works fine.

PS: this is a duplicate https://github.com/James-Yu/Atom-LaTeX/issues/178

**Comment by ashthespy** [comment]
@Fredastair For some reason it's not finding your [root file](https://github.com/James-Yu/Atom-LaTeX#root_file). Try setting it explicitly and it should find it fine then.
let me know,

**Comment by ashthespy** [comment]
Closing this due to lack of response, feel free to post if you run into it again.
