### ISSUE TITLE
Repo history seems messed up?

### ISSUE THREAD

**Issue by ashthespy** [James-Yu/Atom-LaTeX#208]
@James-Yu Not entirely sure what happened, but I don't see my fork (or any forks) of this repo any more?
My fork instead seems to point to instead to [yangzhl/Atom-LaTeX](https://github.com/yangzhl/Atom-LaTeX/)
![image](https://user-images.githubusercontent.com/16233271/62113721-608a1e80-b2b5-11e9-8f87-25b95c0b6a74.png)

**Comment by James-Yu** [comment]
It seems that the repo is messed up when I was configuring my GitHub account, yet I'm not certain about how to restore the fork dependencies. Any idea?

**Comment by ashthespy** [comment]
^ I have found that dropping a line to [github support](https://github.com/contact) explaining what happened can do wonders in such cases..

**Comment by James-Yu** [comment]
@ashthespy it seems that you are the executive maintainer of this project. Do you mind me try to transfer the ownership of this repo to you on GitHub and the Atom package site?

**Comment by ashthespy** [comment]
Oh what does that even mean? But sure, as long as we can still borrow ideas from LaTeX-Workshop ;-)

Speaking of - have you considered keeping the LaTeX and viewer part (command parsing, suggestions, log parsing, snippets, linting) more generic and in a separate module, and then adding specific wrapper for Atom/VS code for editor specific stuff?

**Comment by James-Yu** [comment]
It requires you to first (temporarily) remove your fork of this repo, then I can transfer the ownership to you. I suppose Atom-LaTeX extension will have its ownership automatically transferred, according to the flight manual.

In terms of modularization, I would like to do so but it requires a major overhaul of the code, which I am afraid not have enough time on it.

**Comment by ashthespy** [comment]
Have renamed my repo - should be good to go!

**Comment by ashthespy** [comment]
> Hi there Ash,
> Thanks for writing in and I'm sorry for the time taken for us to get back to you!
> 
> I've looked through the repository's logs and it appears that it was briefly set to private on 2019-07-29 via the repository's settings. It was set back to public 47 seconds later but the problems you've described are all the result of this change:
> 
> https://help.github.com/en/articles/setting-repository-visibility#making-a-repository-private
> 
> As you see in the screenshot in our documentation, we warn that forks, stars, and watchers will be lost. I'm really sorry but we're not able to recover and reassociate that lost data with the repository.
> 
> Again, I'm sorry for the bad news, but I hope helps clear up what happened Do let me know if you have any other questions.
> 
> Thanks,
> Steve

@James-Yu I guess that is what happened?
