### ISSUE TITLE
feature request: execute commands on successful/unsuccessful builds

### ISSUE THREAD

**Issue by wiiareonfire** [James-Yu/Atom-LaTeX#21]
It seems a bit unnecessary that the Atom-LaTeX panel constantly takes up space while working with LaTeX files. If it were an option to, on a successful build, automatically hide the panel to maximize editor screen space, I know it would have at least one user.

Also, the panel links to the raw log, which opens a new document containing the log information. Closing this document creates the prompt for " 'untitled' has changes, do you want to save them?", to which my answer is almost always no, so running into small build issues slows down my workflow. 

However, pdflatex (not sure about other toolchains) outputs a formatted log that is saved as a ".log", and even though I typically wouldn't want to keep the log (I use the option to clean the auxiliary files after building), I'd rather look through that if I had an issue. Not only is it formatted, but it also doesn't prompt for saving changes before closing. 

I think a solution to both of these minor gripes would be allowing the user to execute commands based on how a particular build completed (or failed to). For example, I would configure it so that on a successful build, the panel is hidden and the auxiliary files are cleaned, while on an unsuccessful build, I would want to forgo cleaning the aux files, and instead open the .log file over my pdf viewer. I'm fairly sure that other people could make use of this in ways I can't think of, and I can't seem to find any sort of workaround at the moment, so I think it would be a useful feature for the package.

**Comment by James-Yu** [comment]
First I agree with your suggestions on panel display and raw log. Will make corresponding changes shortly.

As to the customized command chain, it is more an upstream feature request than Atom-LaTeX. It is not very possible for an extension to implement such a great feature for the general Atom editor. I would recommend submitting an issue to Atom with reference to [vscode task](https://code.visualstudio.com/docs/editor/tasks), which I think would be a counterpart/example.

**Comment by James-Yu** [comment]
I will temporarily close this issue. Please feel free to go on the discussion and re-open it if needed.

The changes made will be live in few days. #13
