### ISSUE TITLE
Build after saving  - Trigger from other file types

### ISSUE THREAD

**Issue by ashthespy** [James-Yu/Atom-LaTeX#22]
I use TikZ quite often, creating separate `.tikz` files and linking them into my main document. Also of late, been tinkering with classes, and am lazy to save + build  each time.

I realise that this isn't something a lot of people will use, so I hacked together support to read the `.latexcfg` files for a list of file types to trigger the 'Build after saving` (56e942831e29b9ec7bb1efec2a10f21b56c817c4)

PS: First attempt at CofeeScript, so may not be the most polished implementation!

**Comment by James-Yu** [comment]
Thanks for the contribution. Do you think it is proper for the extension to by default consider `.tikz` file the same as `.tex` files? If so, maybe we can avoid adding a new key to either settings or to `.latexcfg`. Discussion appreciated!

**Comment by ashthespy** [comment]
For TikZ, I'd agree that it could be considered the same as LaTeX, but for `.cls` (classes), I am unsure. Also, KnitR uses `.Rnw` for example. 
I'd propose that this be an "Advanced Setting"  - avoid complicating the main settings and leave it in the `.latexcfg` file.  
This would also help in future proofing, in helping set specific grammars for TikZ/classes based on the file type?

On a side note, [LaTeXTools for SublimeText](https://github.com/SublimeText/LaTeXTools#support-for-non-tex-files) seems to also make the distinctions between these file types, albeit for direct compiling.

**Comment by James-Yu** [comment]
I will check how they did for ST3, and "steal" the good idea :p

**Comment by James-Yu** [comment]
It should work fine now. Please have a test.

**Comment by ashthespy** [comment]
Works great! The pop up to compile either the current file or the `root` LaTeX file is a nice addition.

What would be icing on the cake would be syntax highlighting. This could be hard coded for now in the [`latex.cson`](https://github.com/James-Yu/Atom-LaTeX/blob/master/grammars/latex.cson#L2) file for the more "common" custom file types - `.Rnw` and `.tikz`
Meanwhile, I am looking at porting the few TikZ specific grammar from a [Textmate TikZ bundle](https://github.com/lasersox/tikz-tmbundle/blob/master/Syntaxes/TikZ.tmLanguage), but no promises about the time frame! ;-)

**Comment by James-Yu** [comment]
Is this what you want?

**Comment by James-Yu** [comment]
And this? XD

**Comment by ashthespy** [comment]
Ah, my interest in more in TikZ, but kudos for the work on the plugin! :-)
