### ISSUE TITLE
Bad default execution parameters for latexmk

### ISSUE THREAD

**Issue by astewartau** [James-Yu/Atom-LaTeX#23]
The default parameters for latexmk are given by the plugin as follows:

`-synctex=1 -interaction=nonstopmode -file-line-error -pdf`

These parameters cause the following error to be returned by Latexmk:

```
Command failed: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf test
Latexmk: -synctex bad option
Latexmk: -interaction bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information
```

This is because -synctex and -interaction are not valid options for latexmk. See [here](http://mirror.aarnet.edu.au/pub/CTAN/support/latexmk/latexmk.pdf).

I propose that the default parameters should simply be `-pdf` instead.

**Comment by James-Yu** [comment]
I'm sure you are using an ancient version of latexmk, e.g., the one shipped with Ubuntu, which dates back to 2011. Please update using recent version of texlive.

If this is not the problem, please provide your os, Tex, and latexmk version info.

**Comment by James-Yu** [comment]
See following links for references.

https://github.com/LaTeXing/LaTeXing/issues/37
http://personal.psu.edu/jcc8//software/latexmk-jcc/versions.html

**Comment by astewartau** [comment]
Hi James, thanks very much for the advice! However, I've checked my version and the output is as follows:

```
C:\Windows\System32>E:\Development\Tools\latexmk\perl\perl\bin\perl.exe -S E:\Development\Tools\latexmk\latexmk.pl      
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.

Latexmk: No file name specified, and I couldn't find any
Use
   latexmk -help
to get usage information
```

I am running Windows 10 Pro 64-bit, with LaTeX Version 3.14159265-2.6-1.40.17 (MiKTeX 2.9).

**Comment by James-Yu** [comment]
Hmm interesting. I've tested on both Linux and windows with MikTeX. Neither generates the problem. I would suggest you change your local setting for the arguments, as it seems to be a local problem.

Will go on investigating tho.

**Comment by James-Yu** [comment]
Btw, MikTeX ships latexmk by default. You may want to try that first. Calling the perl script directly sometimes cannot recognize the command line parameters correctly.
