### ISSUE TITLE
Preview without black borders

### ISSUE THREAD

**Issue by aa-b** [James-Yu/Atom-LaTeX#25]
Hi,

it is not an issue. It is a wish.
It would be nice if the pdf-preview in the tab would be without the black borders.
This is what one gets by using the latex-plus package.

Thank you
nic

**Comment by James-Yu** [comment]
Can you please provide screenshot? The desired one is also preferred.

**Comment by aa-b** [comment]
The screenshots are attached.

Am 21/03/2017 um 16:33 schrieb James Yu:

**Comment by ashthespy** [comment]
See comparison
Left is [`pdf-view`](https://github.com/izuzak/atom-pdf-view)

![Comparison Image](https://cloud.githubusercontent.com/assets/16233271/24156457/de0bf1b8-0e56-11e7-8687-a04fa6c26b4e.png)

**Comment by James-Yu** [comment]
@aa-b Sorry the attachment is not available.

@ashthespy I did not see much difference. If you refer to the gray spaces at sides of the pdf, there is a `automatic width` option in the dropdown menu displaying `80%`. Is that what you need?

**Comment by aa-b** [comment]
Sorry for some reason I can not upload files.
I'm getting: Something went really wrong, and we can’t process that file. 
Can I send the screenshots per email?

**Comment by James-Yu** [comment]
imgur is preferred. tho email is ok.

**Comment by aa-b** [comment]
http://imgur.com/kwYayTV
http://imgur.com/Sr7nvIY

**Comment by James-Yu** [comment]
Hmm I get what you mean... I will need to dive into the viewer code of pdf.js for modifications. This is not on the top of priority list, yet I will check.

**Comment by ashthespy** [comment]
@James-Yu  
The options is:
```` * @property {boolean} removePageBorders - (optional) Removes the border shadow````

**Comment by James-Yu** [comment]
Fix merged.

**Comment by James-Yu** [comment]
Just checked the no-border viewer and I have to say it is much better than the previous one IMO :p
