### ISSUE TITLE
Handling multiple projects

### ISSUE THREAD

**Issue by ashthespy** [James-Yu/Atom-LaTeX#31]
More of an enhancement than an issue - It's to do with working with multiple documents in parallel.
 
My typical folder/project structure looks something like below:
```
.
└── Document_1
    ├── Img
    ├── .latexcfg
    ├── Document_1.tex
    └── Document_1_Chapter1.tex 
└── Document_2
    ├── Img
    ├── .latexcfg
    ├── Document_2.tex
    └── Document_2_Chapter1.tex
```
Say I work on `Document_1.tex` for a while, and then switch to `Document_2.tex`, unless I manually pick the `LaTeX Root` via the `Set LaTeX Root` icon in the toolbar, the `.latexcfg` in the `Document_2` folder is ignored. So naturally, all configurations still points to `Document_1`, and does not update to the `.latexcfg` in the `Document_2` folder.

One method of overcoming this would be to when reading the `.latexcfg` to add an extra key of `rootdir` and counter check if the `rootdir` of the current editor file and the `.latexcfg` match in [`findMainSequence()`](https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/manager.coffee#L48).
What do you think?

**Comment by James-Yu** [comment]
I am in doubt of Atom's decision on allowing multiple root directories in a same workspace. Let me find a workaround for this issue.

**Comment by James-Yu** [comment]
Now package will first check the directory where the active editor points to for the config file before iterating through all opened roots.
