### ISSUE TITLE
Busy Indicator

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#33]
Building a large document with a toolchain like pdflatex-biber-pdflatex-pdflatex-showdocument can take some time. It would be nice to have a busy indicator such that one can see that something is going on. I know that this package tries to avoid dependencies, but in this case I would propose the following:

There already is the package https://github.com/steelbrain/busy-signal. This one is pretty much installed on most Atom instances, since it is a dependency of linter (or linter-ui-default). If I recall correctly, Atom-LaTeX optionally does something with minimap if installed. A similar, optional, only when already installed feature could be to utilize the busy-signal package.

**Comment by James-Yu** [comment]
We already have one just next to the toolbar text. It will rotate when something is happening. Can you please raise other reasons to migrate besides compatibility? Thanks.

TBH I am slightly against developers bundling a lot of things for some reason. I installed linter but not busy-signal because of that. I would also want to remove the linter default theme but the package won't work if so.

**Comment by exploide** [comment]
Oh, the gearwheel is rotating.. Haven't noticed so far. Ok, further action isn't urgent.

In general, I agree that a big dependency graph can easily lead to problems and make things complicated. On the other hand, reinventing the wheel every time might also have its problems. Especially when things become inconsistent, users can easily be confused. Having each package showing the busy indicator somewhere different, is one example for this. So I like a set of common base packages, like linter is doing. And I thought relying on busy-signal is rather uncomplicated. But as you like.. At least there is something showing progress..

**Comment by James-Yu** [comment]
Thanks for the comments. When necessary, I will consider adding that support.

This might be one downside for community driven software development :p
