### ISSUE TITLE
PDF rewinds to page 1 on rebuild

### ISSUE THREAD

**Issue by dpo** [James-Yu/Atom-LaTeX#37]
After a recent update, the PDF file rewinds to the very beginning every time I save and the document is recompiled. That is quite annoying and distracting. However, I don't see a setting for it. Is that intentional?

Thanks!

**Comment by James-Yu** [comment]
There is no recent updates that change this behavior. As no other users report similar problems, I would suppose it is related to your computer's configuration. With the current information, I cannot identify the problem.

**Comment by dpo** [comment]
How can it be related to my configuration? What would affect that behavior?

**Comment by James-Yu** [comment]
I have no idea. I cannot reproduce the problem.
