### ISSUE TITLE
/bin/sh won't run pdflatex

### ISSUE THREAD

**Issue by NateJackDev** [James-Yu/Atom-LaTeX#38]
I can't find a solution with the default configuration 
Error:
Command failed: pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main
**/bin/sh: pdflatex: command not found**

For some reason I can run pdflatex fine in bash, but in /bin/sh I can't.
How do I get /usr/sh/ to run pdflatex to get the pdf view in atom?

**Comment by James-Yu** [comment]
This is an upstream problem. How do you open Atom?
