### ISSUE TITLE
arara support?

### ISSUE THREAD

**Issue by kenNash** [James-Yu/Atom-LaTeX#4]
Hi there!

Is there a plan to support arara (instead of latexmk)?

TIA
--
kenNash

**Comment by James-Yu** [comment]
In fact Atom-LaTeX already support using custom toolchain to build LaTeX. Here I'll show you the steps to use arara.

- Open Atom-LaTeX setting page.
- Select `custom toolchain` in the first dropdown menu.
- Enter `arara %DOC -v` in `Custom toolchain commands` editbox.
  - `%DOC` represents the root document. `-v` outputs compiler log for parsing.
- Create your own arara directives in the root file.
- Profit!

You may play around with `custom toolchain commands`. The default setting is the same with arara with the following directive:
```
% arara: pdflatex: { shell : yes }
% arara: bibtex
% arara: pdflatex: { shell : yes }
% arara: pdflatex: { shell : yes }
```

**Comment by kenNash** [comment]
Thank you so much James, for your prompt response!



> On 17 Feb 2017, at 17:03, James Yu <notifications@github.com> wrote:
> In fact Atom-LaTeX already support using custom toolchain to build LaTeX. Here I'll show you the steps to use arara.
> 
> Open Atom-LaTeX setting page.

Actually my first problem arises here, since I can’t find the setting page. This is what I see (no Settings button…):






—
kenNash

**Comment by kenNash** [comment]
> On 17 Feb 2017, at 17:03, James Yu <notifications@github.com> wrote:
> 
> In fact Atom-LaTeX already support using custom toolchain to build LaTeX. Here I'll show you the steps to use arara.
> 
> Open Atom-LaTeX setting page.
> Select custom toolchain in the first dropdown menu.
> Enter arara %DOC -v in Custom toolchain commands editbox.
> %DOC represents the root document. -v outputs compiler log for parsing.
> Create your own arara directives in the root file.
> Profit!
> You may play around with custom toolchain commands. The default setting is the same with arara with the following directive:
> 
> % arara: pdflatex: { shell : yes }
> % arara: bibtex
> % arara: pdflatex: { shell : yes }
> % arara: pdflatex: { shell : yes }

Thank you James: got it!
(Please, ignore my previous email.)

Thank you again. ;-))

—
kenNash

**Comment by ashthespy** [comment]
I have a small issue when I user `arara` 
I have set custom tool chain commands `arara %DOC -v` and my output pdf is generated fine, but an error gets thrown up while building:
`Failed Building LaTeX (code null)` from [here]( https://github.com/James-Yu/Atom-LaTeX/blob/95098f4dcac6685f9682565fa3c7ee34519f0775/lib/builder.coffee#L44). 
It's more an niggle than an actual functional issue, the file actually compiles fine,is displayed, and my logs are written fine.

**Comment by onekk** [comment]
Any news about arara support?

I have used this package and the only difficult was the build phase.

The argumentation about the implementation difficult is somewhat false.

if you set arara the only command to issue is "arara -v Filename", all the multiple passes and other things are done by arara, the only suport is the pdf visualization with synctex support.

Regards

Carlo D.
