### ISSUE TITLE
Use watchers for file changes?

### ISSUE THREAD

**Issue by ashthespy** [James-Yu/Atom-LaTeX#41]
Poking around the automagic suggestions for LaTeX commands, I see that all `\input{}` [files are opened](https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/autocomplete/command.coffee#L84) and scanned for suggestions. While this is nice, it currently happens each time the autocomplete provider is invoked. 
This does cause some concern when working with large files with multiple inputs - though I don't have any noticeable slow down at the moment.

Would it be prudent to use something like [`watchFile`](https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener) or Atom's [`onDidChange`](https://atom.io/docs/api/v1.15.0/File#instance-onDidChange) or better yet [`chokidar`](https://github.com/paulmillr/chokidar) and update the suggestions list only when there are changes to these input files? 

What do you think?

**Comment by James-Yu** [comment]
Thanks for the suggestion. That might be a big change to how the file scanning works. I myself welcomes this improvement, yet it is not on the top of priority list.

**Comment by James-Yu** [comment]
TBH I will try to port this to the VS Code extension first, and see if it can be easily ported back.

**Comment by ashthespy** [comment]
Yep, low priority indeed! This should have the `enhancement` label and not bug :-)
I had quick peek, and it would seem that [VSCode already uses chokidar](https://github.com/Microsoft/vscode/tree/master/src/vs/workbench/services/files/node/watcher/unix) unlike Atom that has [issues on Windows with `watchFile` ](https://github.com/atom/atom/issues/3365)

**Comment by exploide** [comment]
Probably there will be an official API soon, since the implementation of the language-server protocol requires something like this. https://github.com/atom/atom/issues/14163

**Comment by ashthespy** [comment]
Yeah, I saw that a few days back. 

In the interim, I have implemented a `chokidar` based watch system directly in PR #47 :-)
