### ISSUE TITLE
Single-file knitr projects do not build properly

### ISSUE THREAD

**Issue by mathuin** [James-Yu/Atom-LaTeX#42]
I have a project which has a single knitr file named `weightpaper.Rnw`.  There are no other `.tex` or `.Rnw` files in the directory.  I have created a `.latexcfg` with the following contents:
```
{
    "latex_ext": [
        ".tikz",
        ".Rnw"
    ]
}
```
I open the knitr file, and click the build icon at the bottom.  I get a blue notification that this file has been set as the root file, and a red notification reporting a failure to build.  The contents of the red notification:
```
Command failed: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf weightpaper.Rnw
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
      'weightpaper.pdf'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder  "weightpaper.Rnw"'
------------
Latexmk: Log file says output to 'weightpaper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
```

I had expected something like this to be executed before the call to `latexmk`:  `Rscript -e "library(knitr); knit('$<')"`

Am I doing something wrong?  What should I be doing instead?

**Comment by ashthespy** [comment]
Latexmk as far as I know doesn't have inbuilt support for `kniter`.
To compile, you could either set a custom command, or try [`arara`](https://github.com/cereda/arara) - and a [custom rule](http://tex.stackexchange.com/a/202487/37433)

**Comment by ashthespy** [comment]
@James-Yu maybe should re-open this until confirmation that it works?

**Comment by mathuin** [comment]
I'm using LaTeX for a bunch of stuff, including my thesis, so I ended up using the Docker container which builds my thesis to build this paper.  It worked well, but went way outside the scope of this package so I think it's probably a bad thing to recommend to others. :-)

Were I to recommend a fix or write a PR, I would rewrite the `"latex_ext"` object to be a hash, with file types as keys and one-line commands as values.  I would then have had something like this:

````
{
    "latex_ext": [
        ".tikz": "some command that converts foo.tikz to foo.tex",
        ".Rnw": "Rscript -e "library(knitr); knit('%DOC')""
    ]
}
````

The package could then run the pre-processing commands whenever those files were modified and saved, and in my case the LaTeX root would then be pointed at the output of the pre-processing command for my source file.

**Comment by mathuin** [comment]
On further reflection, I think a better way to handle this would be to combine `toolchain` and `latex_ext` into one object: `toolchains`.  `toolchains` would have the key-value definitions mentioned above for `latex_ext` but with the existing toolchain used as the value for the key `.tex`.  This allows for the deprecation of the `toolchain` object and its associated bits while not breaking existing code.  I haven't written CoffeeScript, but I am willing to give it a try.

**Comment by James-Yu** [comment]
As main functionality for the extension is to provide LaTeX support, the variants are not considered as important. I'd recommend you create customized `.latexcfg` files to control the local behavior of different files. E.g., you may put all `.tikz` files in a same subfolder and create a `.latexcfg` file with the specific toolchain. In this case whenever you edit a file or changed one you may run build/build here to refresh.
I personally do not use either `.tikz` or `.Rnw` so these are only my guesses.

**Comment by ashthespy** [comment]
#### Option 1
Am I oversimplifying this, or wouldn't a `.latexcfg` like this work fine?
```
{
  "root": "path/to/my/file.Rnw",
  "toolchain": "Rscript -e \"library(knitr); knit('%DOC')\" && latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf %DOC",
  "latex_ext": [".Rnw"]
}
```
The [builder should parse](https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/builder.coffee#L140) the `toolchain` key and split them into sequential commands at `&&` 

Once issue I foresee though is that the `%DOC` placeholder by default expects the root file to be `.tex` so the the second `%DOC` in the `toolchain` would be expanded to `file.Rnw` in this case and not `file.tex`

#### Option 2
Repeating from my last comment, but I'd highly recommend [`arara`](https://github.com/cereda/arara) for this case!
With a rule](http://tex.stackexchange.com/a/202487/37433) such as:
```
!config
identifier: knitr
name: knitr
commands: 
- <arara> RScript -e "library(knitr); knit('"@{source}"', output='"@{target}"')"
- <arara> xelatex "@{target}"
arguments: 
- identifier: source
  flag: <arara> "@{parameters.source}"
  default: <arara> "@{getBasename(file)}".Rnw
- identifier: target
  flag: <arara> "@{parameters.target}"
  default: <arara> "@{getBasename(file)}".tex
```
Then with the directive in the `.Rnw` file as `% arara: knitr`
and setting your toolchain to `arara %DOC -v` it should produce the pdf directly by running build :-)

**Comment by James-Yu** [comment]
@ashthespy Thanks a lot for the summary! I will add a reference to this answer in the readme.

@mathuin Can you please check if the methods suggested by @ashthespy above work for you? Thanks.

**Comment by mathuin** [comment]
The first option works, with some minor sed magic which replaces the Rnw with tex.

````
{
    "root": "example.Rnw",
    "toolchain": "Rscript -e \"library(knitr); knit('%DOC')\" && latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf $(echo %DOC | sed -e \"s/Rnw/tex/\")",
    "latex_ext": [".Rnw"]
}
````

I was unable to get `arara` to do anything useful after half an hour of tweaking -- the configuration it requires is a bit too much work for something I'm never going to use, so maybe someone else can get it to work.

**Comment by James-Yu** [comment]
Glad at least it works for you!

**Comment by ashthespy** [comment]
Sorry for the clutter, I need to understand git flow better. :-(
But, that should fix it, will submit a PR soon!

**Comment by ashthespy** [comment]
With this PR merged, I'd reckon the following configuration would work for `.Rnw` files 
```
{
  "root": "path/to/my/file.Rnw",
  "toolchain": "Rscript -e \"library(knitr); knit('%DOC.Rnw')\" && latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf %DOC",
  "latex_ext": [".Rnw"]
}
```

Cheers! :-)
