### ISSUE TITLE
Enhancement - Possible to Syntex via mouse actions?

### ISSUE THREAD

**Issue by ashthespy** [James-Yu/Atom-LaTeX#43]
Would it be possible to trigger Syntex via some form of mouse action instead of (or additional to) the current key map and context menu? 
Maybe a `alt + click` or something cross platform friendly?

**Comment by James-Yu** [comment]
I'm a bit skeptical to `alt`+click as the reverse one is `ctrl`/`cmd`+click. Meanwhile, the latter is reserved for multi cursor support in Atom.

In fact I'm not sure if it is possible to add mouse listeners to editors with Atom API. Or maybe dirty hacks in the DOM is required.

**Comment by ashthespy** [comment]
Yep, I was looking into it a bit last night, and until Atom exposes an api for mouse actions, this would be not worth the effort. 
There are some packages that access the DOM directly ( [The `hyperclick` package for example](https://github.com/facebooknuclide/hyperclick/blob/master/lib/HyperclickForTextEditor.js#L115) but again, don't think it would be worth the effort in this case.
