### ISSUE TITLE
Spell-check

### ISSUE THREAD

**Issue by farzad90** [James-Yu/Atom-LaTeX#48]
I added text.tex.latex to the grammars in the spell-check setting, but still can't get any highlighted misspelled word on Atom-Latex! Is there anything else wrong?

**Comment by James-Yu** [comment]
Did you also input your locale? e.g. `en-US`

**Comment by farzad90** [comment]
my local is en-US, and with or without that the issue still exits! here's the screenshot; last line is surely an error but not highlighted or underlined!

<img width="533" alt="screen shot 2017-04-10 at 12 12 48 am" src="https://cloud.githubusercontent.com/assets/27193257/24849876/90b4b518-1d82-11e7-9644-d077ec588001.png">

**Comment by James-Yu** [comment]
The syntax highlight suggest that these words are in math mode.
If this is not the problem, the problem should be on `spell-check` side. This extension does not provide any explicit spell check features.

**Comment by farzad90** [comment]
Here's also the spell-check setting screen-shot:

<img width="335" alt="screen shot 2017-04-10 at 12 15 52 am" src="https://cloud.githubusercontent.com/assets/27193257/24849961/f7b97654-1d82-11e7-9ced-a29dabfde529.png">

**Comment by James-Yu** [comment]
I cannot reproduce the problem. The screenshots are attached.
Does your spell checker works with other files, e.g., markdown or plain text?

![image](https://cloud.githubusercontent.com/assets/4210342/24850027/04452df4-1e01-11e7-9435-05b7a49077a9.png)

**Comment by farzad90** [comment]
You are right! my spell-check doesn't even work on plain text, let alone Atom-Latex.
<img width="387" alt="screen shot 2017-04-10 at 12 24 52 am" src="https://cloud.githubusercontent.com/assets/27193257/24850271/3d51349e-1d84-11e7-8008-1b5da7acc154.png">

**Comment by James-Yu** [comment]
It is either a local configuration problem, or a bug in [`spell-check`](https://github.com/atom/spell-check). For the latter case, I would recommend you submit an issue at its repo.
