### ISSUE TITLE
Documentation for running with external ".bib" file

### ISSUE THREAD

**Issue by Jvinniec** [James-Yu/Atom-LaTeX#51]
First, fantastic tool! This has replaced TexWorks for me. I have one suggestion though (not really an 'issue' but I don't know where else to post it). Being unfamiliar with Atom and this package, it took me the better part of an hour to figure out how to build my PDF when my references are stored in an external ".bib" file. Basically, I needed it to run the following four commands sequentially in order to include and compile my references:
```
pdflatex mydoc
bibtex mydoc
pdflatex mydoc
pdflatex mydoc
```
I eventually figured out I could do this by changing the following line in my .latexcfg file
```
"toolchain" : "%TEX %ARG %DOC"
```
to
```
"toolchain" : "%TEX %ARG %DOC;bibtex %DOC;%TEX %ARG %DOC;%TEX %ARG %DOC"
```
Is it possible to update the documentation to reflect how to run multiple commands on the project?

**Comment by ashthespy** [comment]
Hi there,
I made a small summary about running multiple commands on a different issue ( #42 ) but shall add it to the main documentation as well. 

For your particular use case, I'd recommend looking into either [`latexmk`](https://www.ctan.org/pkg/latexmk/?lang=en) if you are on Linux/Mac or ['arara'](https://www.ctan.org/pkg/arara) if you are on Windows and don't have `perl` installed. 
Using one of those as your tool chains should result in the final PDF automatigically ;-)

In fact, the default 'auto' toolchain setting on the package uses tires `latexmk` before falling back on the custom toolchain.
![image](https://cloud.githubusercontent.com/assets/16233271/24900076/debfa2ce-1ea2-11e7-95fb-4dce543fef8a.png)
 
With `arara` a little more work is required, but I find it more powerful for my needs:
Similar to `TeX` magic commands, set your `arara` directives as:
```
% arara: pdflatex: {synctex: no}
% arara: bibtex
% arara: pdflatex
% arara: pdflatex: {synctex: yes}
```
And then set your custom toolchain to 
`arara %DOC -v`

**Comment by Jvinniec** [comment]
Thanks for the quick response! I removed the "toolchain" completely from my '.latexcfg' file and it looks like it works fine. Guess I just needed to read the documents more closely. I'll go ahead and close this issue since I think it's more my fault than the documentation. Thanks again and keep up the good work!
