### ISSUE TITLE
Set the following file as main file popup

### ISSUE THREAD

**Issue by WillyWinkel** [James-Yu/Atom-LaTeX#53]
I am quite happy with the plugin. I use it for syntax highlighting and autocompletion, since I have a buildscript which allready works I didnt bother changing that.
My problem is that every time I enter a '\' a popup occures that basically says:

    Set the following file as main file
    $path to my root which i set in .latexcfg$
    Reason: The configuration file setting.

Is there any way to stop that popup? I dont see the point in it

**Comment by ashthespy** [comment]
Yes, that is bug, it has been fixed in a PR, should be fixed in next update :-)
