### ISSUE TITLE
Kill does not work

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#54]
Recently a pdflatex process went crazy and I wanted to stop it using an abort feature of Atom-LaTeX. I found the kill command in command palette, but it did nothing to the process. I had to kill it in htop (with SIGTERM).

**Comment by ashthespy** [comment]
Can confirm similar behavior with Windows 10, I initially assumed it was my system specific config so set a timeout in my tool chain as a temporary workaround.
Will do some poking around, and report my findings.

**Comment by ashthespy** [comment]
Had the chance to do some digging.

The [package](https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/builder.coffee#L38) currently uses [`child_process.exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) which invokes a shell and then executes commands in that shell. So the `pid` that is being killed when the [`Kill`](https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/builder.coffee#L104) command is toggled doesn't match the `pid` of the actual LaTeX toolchain compiler `pid` and hence doesn't get killed.

This can be overcome by switching to [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) - but I don't have time to work on this right now.

**Comment by ashthespy** [comment]
Should be fixed with a551a3d4d9300026ddf453053f155360dbd885ce :-)

**Comment by ashthespy** [comment]
While playing around today, I realised that the children of the spawned command aren't killed when using the inbuilt `child_process.kill()` method. 

This gets annoying when using `arara` - which spawns a new child process for each build rule.  Thus while the `arara` instance is killed, the hung `pdflatex` instance still continues.

Does `latexmk` also do this? Any ideas?

**Comment by exploide** [comment]
I can confirm that killing the latexmk process using Atom-Latex' kill functionality does not immediately stop everything. A pdflatex process is still running, creating a pdf file. It lacks stuff like table of content and similar because the second run don't get invoked.

**Comment by ashthespy** [comment]
Thanks for the confirmation.
This should take care of it now. I tested it and it works fine on Windows, would you be able to test the fix on Linux?

**Comment by exploide** [comment]
Since this involves downloading the pr-branch manually and installing it in an atom dev environment, it requires a few more steps for me. Maybe I find the time this evening.

**Comment by ashthespy** [comment]
Thanks!
Btw, you could also do it the lazy way:
1. `Settings`→`Atom-LaTeX`→`View Code`
2. Copy paste the appropriate lines and reload Atom (`ctr`+`shift`+`F5`)

**Comment by exploide** [comment]
Fascinating, this must be why it is called the hackable editor :D I thought the View Code button will open a browser showing this Github repo.

Unfortunately, the processes are not killed. Same behavior as described above. Since I was not sure the reloading worked, I reopened atom, but the behavior doesn't change.

**Comment by ashthespy** [comment]
Ah. I am at a loss (for now) then. 
Will dig deeper, hopefully someone with more unix experience chimes in in the mean time!

**Comment by exploide** [comment]
Maybe because pkill -P only gets the immediate child process and not the whole tree including grandchild processes.

**Comment by exploide** [comment]
Maybe this could work: http://azimi.me/2014/12/31/kill-child_process-node-js.html

**Comment by ashthespy** [comment]
I think I know the issue, I left in the `@currentProcess.kill()` as a backup - but that would just terminate the parent before the async call to `cp.exec()` is completed. 
Could I request you to try this out sometime? Outputs on the dev console (`ctr` + `shift` + `i`)
```
# Kill entire process tree
if process.platform is 'win32'
  killcmd = "taskkill -pid #{@currentProcess.pid} /T /F"
else
  killcmd = "pkill -P #{@currentProcess.pid}"
cp.exec(killcmd, (error, stdout, stderr) ->
  console.log error if error?
  console.log "> #{killcmd}\n\n#{stdout}" if stdout?
  console.log stderr if stderr)

```

**Comment by exploide** [comment]
Can confirm it works, no pdf is created and no pdflatex processes remain running :) 

killProcess now looks like this:
```coffee
  killProcess: ->
    @cmds = []
    if @currentProcess?
      @latex.logger.log.push({
        type: 'warning',
        text: "Killing running LaTeX command (PID: #{@currentProcess.pid})"
      })
      # Kill entire process tree
      if process.platform is 'win32'
        killcmd = "taskkill -pid #{@currentProcess.pid} /T /F"
      else
        killcmd = "pkill -P #{@currentProcess.pid}"
      cp.exec(killcmd, (error, stdout, stderr) ->
        console.log error if error?
        console.log "> #{killcmd}\n\n#{stdout}" if stdout?
        console.log stderr if stderr)
```

If it is expected, that atom shows the following error after aborting, it seems to work.

```
Failed Building LaTeX (code 12).
Latexmk: This is Latexmk, John Collins, 16 May 2017, version: 4.53a.
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
      'msc-thesis.pdf'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape -recorder  "msc-thesis.tex"'
------------
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 0.05859375
      Refer to 'msc-thesis.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
```

**Comment by ashthespy** [comment]
I agree, will change it to `Build Aborted` :-)
