### ISSUE TITLE
Uncaught TypeError: Array.prototype.indexOf called on null or undefined

### ISSUE THREAD

**Issue by fhchl** [James-Yu/Atom-LaTeX#56]
[Enter steps to reproduce:]

1. Saving a tex file

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.6

### Stack Trace

Uncaught TypeError: Array.prototype.indexOf called on null or undefined

```
At C:\Users\fmheu\.atom\packages\atom-latex\lib\manager.coffee:240

TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (native)
    at Manager.module.exports.Manager.prevBibWatcherClosed (/packages/atom-latex/lib/manager.coffee:240:21)
    at /packages/atom-latex/lib/manager.coffee:220:29
    at Array.map (native)
    at Manager.module.exports.Manager.findDependentFiles (/packages/atom-latex/lib/manager.coffee:214:20)
    at /packages/atom-latex/lib/manager.coffee:162:14)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/atom-latex/node_modules/chokidar/index.js:191:15)
    at FSWatcher._emit (/packages/atom-latex/node_modules/chokidar/index.js:233:5)
    at /packages/atom-latex/node_modules/chokidar/lib/nodefs-handler.js:263:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -2:47.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -2:47.4.0 editor:newline (input.hidden-input)
     -2:46.7.0 intentions:highlight (input.hidden-input)
     -0:29.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:29.1.0 editor:newline (input.hidden-input)
     -0:28.5.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:28.5.0 editor:newline (input.hidden-input)
     -0:28.4.0 intentions:highlight (input.hidden-input)
     -0:28.4.0 core:paste (input.hidden-input)
     -0:27.6.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:27.6.0 editor:newline (input.hidden-input)
     -0:26.9.0 core:move-up (input.hidden-input)
 12x -0:26.7.0 core:move-right (input.hidden-input)
  7x -0:25.4.0 core:select-right (input.hidden-input)
     -0:18.8.0 intentions:highlight (input.hidden-input)
     -0:18.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.23 
atom-clock 0.1.7 
atom-latex 0.7.6 
autocomplete-bibtex 0.7.0 
autocomplete-python 1.8.63 
autoupdate-packages 1.3.1 
busy-signal 1.4.1 
editorconfig 2.2.2 
file-icons 2.1.4 
git-plus 7.7.0 
highlight-selected 0.13.1 
imdone-atom 2.2.5 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
language-markdown 0.21.0 
language-matlab 0.2.1 
language-pfm 0.82.0 
languagetool 0.1.1 
latex-autocomplete 1.0.0 
linter 2.1.4 
linter-coffeelint 1.2.1 
linter-flake8 2.2.1 
linter-proselint 3.2.1 
linter-ui-default 1.2.3 
linter-write-good 0.9.0 
markdown-preview-plus 2.4.9 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
open-terminal-here 2.3.0 
pdf-view 0.57.0 
project-manager 3.3.4 
script 3.14.1 
split-diff 1.3.0 
sync-settings 0.8.1 
tasks 2.6.6 
termination 0.5.0 
wordcount 2.10.4 
Zen 0.16.4 
```

**Comment by ashthespy** [comment]
Hey, 
I am aware of this, made a typo in my last commit, fix is on the way!

**Comment by cnsetzer** [comment]
I am now receiving this error. Error message links to this issue. 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.2


### Stack Trace

Uncaught TypeError: Array.prototype.indexOf called on null or undefined

```
At /Users/cnsetzer/.atom/packages/atom-latex/lib/builder.coffee:37

TypeError: Array.prototype.indexOf called on null or undefined
    at indexOf (<anonymous>)
    at Builder.module.exports.Builder.saveonBuild (/packages/atom-latex/lib/builder.coffee:37:34)
    at Builder.module.exports.Builder.build (/packages/atom-latex/lib/builder.coffee:19:18)
    at /packages/atom-latex/lib/main.coffee:33:48)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:12.3.0 core:save (input.hidden-input)
     -8:54.7.0 application:open (atom-pane.pane.active)
     -8:38.6.0 atom-latex:build (input.hidden-input)
  3x -8:31.2.0 core:undo (input.hidden-input)
  2x -8:22.9.0 editor:newline (input.hidden-input)
  2x -8:22.2.0 core:move-up (input.hidden-input)
     -8:17.9.0 application:open (input.hidden-input)
     -7:54.1.0 core:copy (input.hidden-input)
     -7:51.5.0 core:paste (input.hidden-input)
  2x -7:46.8.0 core:delete (input.hidden-input)
  2x -7:44.8.0 atom-latex:build (input.hidden-input)
     -7:31.8.0 core:save (input.hidden-input)
     -7:29.8.0 atom-latex:build (input.hidden-input)
     -6:16.9.0 core:backspace (input.hidden-input)
     -6:09.6.0 core:paste (input.hidden-input)
  2x -6:05.7.0 atom-latex:build (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.2 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
grammar-token-limit 0.1.1 
intentions 1.1.5 
language-latex 1.1.1 
linter 2.2.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.6.10 
pdf-view 0.61.0 
```

**Comment by ashthespy** [comment]
@cnsetzer 
While the error message is the same, the issue is from elsewhere. 

Could I request you to open up the Dev console (<kbd>`ctrl`</kbd>+<kbd>`shift`</kbd>+<kbd>`i`</kbd>)  and report back the output what the output of `atom_latex.latex.texFiles` looks like when you encounter this error?

**Comment by cnsetzer** [comment]
@ashthespy 

When I open the console and look through, there is no output for `atom_latex.latex.texFiles`. It appears that `atom_latex.latex` has no attribute `.texFiles`. It returns 

```
> atom_latex.latex.texFiles
<- undefined
```

**Comment by ashthespy** [comment]
As expected, the usual questions:
How do you define the [LaTeX root file](https://github.com/James-Yu/Atom-LaTeX#setting-the-latex-root-file), and what does your project structure look like?

**Comment by cnsetzer** [comment]
Ah that's it. It seems that this only happens when I am starting a new project from an exisiting `.tex` file, i.e. where I only have a `*.tex` file in my directory. If I am working with a project that has all of the build/auxiliary files I do not run into this issue. This could be because I have been using the `Build` command rather than `Build Here`, without having an absolute path explicitly defined.

Yes, the `atom_latex.latex.mainFile` is defined as expected, `~/.../file.tex`. My project structure is simply to isolate my latex into its own self-contained directory and edit/build everything there.

**Comment by ashthespy** [comment]
@cnsetzer 
It should still work with just a `*.tex` by trying to automagicly determine which is the main file when running `build` it has nothing to do with the other build/auxiliary files.  Especially so if you have a single 'Atom Project' with just one `file.tex`. Or, even if you have mixed project with code and LaTeX, it should still work, for example take this package's repo structure. Opening `spec/latex_project/main.tex` and hitting build should work.

Could you share more details on your exact project structure that throws this error so I can try reproducing it?

**Comment by cnsetzer** [comment]
@ashthespy 
I would like to, but I'm embarrassed to say I cannot successfully recreate the issue anymore. Though nothing (I know of) should have changed from yesterday to today, when I repeat the steps that I listed above I cannot replicate the error as was happening yesterday. I'm sorry for bothering you with this, I'll let you know if I find out what has happened to change the situation.
