### ISSUE TITLE
Extremely slow build times starting from 0.7.6 update

### ISSUE THREAD

**Issue by johschmitz** [James-Yu/Atom-LaTeX#58]
Something broke for me in 0.7.6 now compiling became extremely slow.
Often I only see a white or gray page in the PDF viewer.

I am not 100% sure if I did the 0.7.5 but the problem started for me in 0.7.6
Now that it is not supported anymore is there a way to downgrade to a lower version?

**Comment by johschmitz** [comment]
I found a solution for the command line:
`apm install <package_name>@<package_version>`
so
`apm install atom-latex@0.7.5`

0.7.5 seems to be running just fine, starting from 0.7.6 something broke.
I am using the custom toolchain option and the custom toolchain command is just `make`

**Comment by ashthespy** [comment]
To answer your last question first - 
From your command line run 
```
apm install atom-latex@<package_version>
```
to downgrade to the version of your choice.

But, I am extremely curious about why your facing such issues. Would you mind helping with some troubleshooting/benchmarks for your use case?
I did some initial profiling and benchmarks and didn't notice any issues.

**Comment by johschmitz** [comment]
Maybe there's some interference between my Makefile and Atom or something like that. What shall I do to find out more about the problem?

**Comment by ashthespy** [comment]
I just went back to `v0.7.5` and ran some timing checks with some of my papers. 
I don't seem to find any difference between `v0.7.6`, `v0.7.6` and `v0.7.7` in compiling times.  

The [significant changes](https://github.com/James-Yu/Atom-LaTeX/blob/master/CHANGELOG.md#076--2017-04-22) b/w `v0.7.5` and `v0.7.6`  are mainly the new folder watching and some changes to the PDF viewer. 

For starters, could you set the `Preview PDF after building process` to `Do nothing` in the newer versions and check if you still have slow times? 

If that doesn't change the slow times, there are some issues with the interaction of your Makefile and the folder watcher routine. Unfortunately, I am on Windows and don't use make, so might take a while for me to help debug.

**Comment by Tobii42** [comment]
I also had massive performance issues with the latest version 0.7.7, but going back to 0.7.5 helped. I'm on Windows 10. The memory consumption was going up once every minute or so and then, suddenly, the CPU went crazy and the memory went down again. A minute later, the whole procedure started again. I would guess it was a memory leak and the garbage collection kicking in.

**Comment by ashthespy** [comment]
I have been looking into performance issues and high CPU usage is an often reported issue when watching large directories/ directories with a lot of files.  


Unfortunately (or fortunately for my normal writing ;-) ) I don't face high usage issues.  However, It might be prudent then to have an option to disable it for people who are having issues? 

What do you all think?

**Comment by johschmitz** [comment]
Did you just change the implementation starting from 0.7.6 or add a new
feature?
If it's the former then I think something is broken.
If it's the later I still don't believe it makes sense to be used in the
current state. I have an i7 machine with 32 GB RAM and very fast SSD. If it
can not run properly even on that machine it would be pretty useless. So
I'm definitely assuming that this is a bug, probably just visible on Linux.
Meanwhile I am sticking with 0.7.5 to get my thesis done.

Am 02.05.2017 16:29 schrieb "Ash" <notifications@github.com>:

I have been looking into performance issues and high CPU usage is an often
reported issue when watching large directories/ directories with a lot of
files.

Unfortunately (or fortunately for my normal writing ;-) ) I don't face high
usage issues. However, It might be prudent then to have an option to
disable it for people who are having issues?

What do you all think?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/James-Yu/Atom-LaTeX/issues/58#issuecomment-298652497>,
or mute the thread

**Comment by ashthespy** [comment]
After some playing around I did notice high CPU usage with v0.7.8 when adding external files into the LaTeX project with Atom open. 

I made some tweaks with the implementation (63c928b) that should fix the slow performance in the next update. 
As a fallback, there is also an option to turn off the folder watching by setting a new key `disable_watcher`  to `true` under `atom-latex` in your user configuration (`config.cson`).

**Comment by Tobii42** [comment]
> After some playing around I did notice high CPU usage with v0.7.8 when adding external files into the LaTeX project with Atom open.

Yes, that could have been the case in my project, too. I think I inserted an external file while the Atom project was open. Thank you so much for your work! I will try out the next version after 0.7.8.

**Comment by ashthespy** [comment]
Changes included in `v0.7.9` - Reopen if you are still facing issues!
