### ISSUE TITLE
Trouble opening preview in separate pane

### ISSUE THREAD

**Issue by jasm32851** [James-Yu/Atom-LaTeX#63]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.7

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /home/james/.atom/packages/atom-latex/lib/manager.coffee:88

TypeError: Cannot read property 'file' of undefined
    at Manager.module.exports.Manager.findMainSelfMagic (/packages/atom-latex/lib/manager.coffee:88:5)
    at Manager.module.exports.Manager.findMainSequence (/packages/atom-latex/lib/manager.coffee:65:21)
    at Manager.module.exports.Manager.findMain (/packages/atom-latex/lib/manager.coffee:42:15)
    at Server.module.exports.Server.httpHandler (/packages/atom-latex/lib/server.coffee:33:26)
    at /packages/atom-latex/lib/server.coffee:12:46)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
```

### Commands

```
     -0:27.6.0 atom-latex:preview-tab (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-latex 0.7.7 
multi-cursor 2.1.5 
pdf-view 0.57.0 
```

**Comment by ashthespy** [comment]
Thanks for the logs - I can now reproduce the error by doing the following

1. Open a .tex file
1. Click `Preview PDF`  in the LaTeX panel
1. PDF opens in new tab pane - and PDF tab is in focus
1. `Package` → `Atom-LaTeX` → `Preview PDF` or `Preview PDF in new Tab`

I will look into adding a fail-safe to avoid this in the future. 

But could I ask why you would like to `Preveiw PDF` when the PDF is already open? 
The `Preview PDF`  is only meant to open the compiled PDF - Don't you mean `Build PDF` if you want to see the compiled changes to your `.tex` file?

**Comment by ashthespy** [comment]
On some further investigation - I can also reproduce this error by doing the following.
1. Add any atom project
1. Add another atom project and open a `.tex` file in the second project.
1. Click Preview PDF in the LaTeX panel
1. PDF opens in new tab in a split pane - and PDF tab is in focus
1. Drag the PDF tab back to the `.tex` pane -  collapsing two panes to one.

Result - PDF does not render with just a grey background and finally a `Unexpected server response`
```
PDF.js v1.6.414 (build: 3b3a179)
Message: Unexpected server response (0) while retrieving PDF "http://127.0.0.1:56240/preview.pdf".
```
There is no error toast popup - but same TypeError in the debugger. 
Strangely, I can't seem to reproduce this in dev mode - need to investigate more!
