### ISSUE TITLE
Command to set current file as root

### ISSUE THREAD

**Issue by simon123h** [James-Yu/Atom-LaTeX#69]
When I work with multiple documents and switch between them, I need to click the home button and dig through a file picker. That takes quite some time and I tend to rather close Atom completely to have the root file evaluated from scratch. A command palette option to "Set current file as root" or at least re-evaluate the root file somehow could ease my workflow on that issue.

Example:
```
/projectFolder
   /subProject1
       main.tex
    /subProject2
       main.tex
```
I open projectFolder in Atom and write some lines in /subProject2/main.tex, compile it, done. Then I'd like to switch to /subProject2/main.tex and work on it. I'd like to just open /subProject2/main.tex in a pane and "set current file as root" via command palette.

**Comment by James-Yu** [comment]
You can `atom-latex:build-here`.

**Comment by ashthespy** [comment]
Any reason why you don't load `subProject1` and `subProject2` as separate Atom projects? 
In that scenario, the plugin will automatically switch and identity the root file each time you switch documents. This would then mean that all other features (PDF Preview, Autocomplete, etc) also seamlessly switch with respect to the `subProject`
