### ISSUE TITLE
Sytax highlighting only first 1000 characters of a line

### ISSUE THREAD

**Issue by Tobii42** [James-Yu/Atom-LaTeX#74]
Hi,

when using the editor, syntax highlighting only works for the first 1000 characters in a line. This can easily be seen when commenting a line with more characters. It stops to be "grey and italic" after 1000 chars. Other highlights such as \cite{} etc. do not work, too.

Example:

%Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod last highlighted character ---->XThis is no longer highlighted :(

**Comment by James-Yu** [comment]
This is a limitation by Atom. We cannot change it by extensions.

**Comment by Tobii42** [comment]
Oh, was not aware of it. Thank you for the answer!

**Comment by ashthespy** [comment]
@Tobii42  check out https://github.com/atom/atom/issues/1667
