### ISSUE TITLE
auto build after save doesn't build current file

### ISSUE THREAD

**Issue by sebschaffrath** [James-Yu/Atom-LaTeX#75]
while saving the document I'm currently editing I expect the auto build after save feature to build this specific file. Instead it builds and shows the same document every time as long as I do not restart Atom. This is very helpful while working on a multi-file document but very annoying while working on different documents simultaneously.

**Comment by ashthespy** [comment]
Could you clarify how you work currently on multiple documents simultaneously? 

The build-after-save build the currently set LaTex root file. So you need to ensure that the package is able to correctly identify the [root file](https://github.com/James-Yu/Atom-LaTeX#setting-the-latex-root-file).

Personally, I'd recommend to have these different documents open as different projects in Atom say:
```
.
└── Document_1
    ├── Img
    ├── .latexcfg
    ├── Document_1.tex
    └── Document_1_Chapter1.tex 
└── Document_2
    ├── Img
    ├── .latexcfg
    ├── Document_2.tex
    └── Document_2_Chapter1.tex
```
However as long as the package is able to identify that the current document has a different root, the feature will work.

**Comment by sebschaffrath** [comment]
I tried to work with my files as you recommended and you're absolutely right.
Thank you for your help!
