### ISSUE TITLE
Allow to open pdf with custom viewer

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#8]
It is quite nice that this package allows to open the pdf file directly after the build process. But it would be even more awesome if one could optionally specify an external pdf viewer like evince, okular, etc.

Additionally it may be worth thinking if opening with https://github.com/izuzak/atom-pdf-view could be an option, too. (while thinking about this, is it worth shipping an own pdf viewer when this package already exists? but this is something different to this issue)

**Comment by exploide** [comment]
Just noticed that this is a duplicate of #1 I'm sorry!
Nevertheless, I consider this a useful feature

**Comment by James-Yu** [comment]
Thanks for the suggestion.

The design idea of this plugin is plug-n-play. External reader programs or pdf-view plugin violate this concept. In addition, I don't think pdf-view provides more or better experience/functionality than the shipped one.

My own experience before coding this plugin is that I cannot make other latex plugins work well with either pdf-view or sumantra. These components are not adhered to the plugin well.
