### ISSUE TITLE
auto-completion for multi-file project doesn't work

### ISSUE THREAD

**Issue by hfenigma** [James-Yu/Atom-LaTeX#80]
This happens to \cite and \ref.
I have tried to set the root file use .latexcfg file like
`{ "root" : "\path\to\root\file.tex" }`
or
`{ "root" : "/path/to/root/file.tex" }`
or
`{ "root" : "../relative/path/to/root/file.tex" }`
or magic comment for sub-files
`% !TEX root = ../relative/path/to/root.file.tex`
None of them works.
The magic comment do works with packages like [latexer](https://atom.io/packages/latexer) or [latextools](https://atom.io/packages/latextools).
And I pretty like the way latexer and latextools to show the completion list, so I can search the title or something if I can not remember the index. It would be perfect if there is an option to switch to this style.

**Comment by ashthespy** [comment]
Could you give me a little more details with regards to how your multi-file project looks like?
I am unable to reproduce the error on my side, so some questions.
1. Does the package throw up an error about not finding a root file? 
2. Or does it find it using some other method? If so, which one? This should be reported when you hit build for instance. 
3. What does your current multi-file project look like?

Atom-LaTeX should normally pop up an autocomplete list with the parsed bib results for `\cite` and parse all TeX files of the current project to get the list of labels for `\ref`

**Comment by hfenigma** [comment]
The project structure looks like 
```
projectFoo/
           bib/
               thesis.bib
           chapters/
                    chapter1.tex(with "% !TEX root = ../main.tex", failed to pop up autocomplete list)
                    chapter2.tex(with "% !TEX root = ../main.tex", failed to pop up autocomplete list)
           main.tex (with \include{chapters/chapter1 and \addbibresource{bib/thesis.bib}}
           .latex.cfg
```
Atom-latex autocomplete do works for single-file projects, it just doesn't show any pop up list for the above project (no error msg as well).

The build is fine as well, just the autocomplete list doesn't pop up, so I have to add the \cite{somekey} manually.

After I created this issue, I noticed the original author of this package switched to VS Code. T__T
So I switched to latex + latexer + language-latex. These three packages works perfectly for me.

**Comment by ashthespy** [comment]
I just had some time to look into this, and this should now work quite will with multi-file and also multiple projects. Give it a spin if you are inclined! :-)
