### ISSUE TITLE
Non .tex files don't work

### ISSUE THREAD

**Issue by simon123h** [James-Yu/Atom-LaTeX#86]
Hi,

For me, non .tex files do not compile, unless I set up everything as documented. I have this issue both on Windows and Debian.

Minimal example: 
- `example.tikz`:
`    \documentclass{article}
    \begin{document}
      Foo Bar
    \end{document}`

- `.latexcfg`:
`    {
      "root": "example.tikz",
      "latex_ext": [".tikz"]
    }`

Both in one folder. I manually set example as a root file in atom-latex, but compilation fails with the message:
`example.tikz: I can't find file 'example'`

Is there something broken?

Also, wouldn't it be nice to have native support for .tikz extensions?

**Comment by simon123h** [comment]
I had a closer look in the code and found line 154 in builder.coffee:
`@escapeFileName(path.basename(@latex.mainFile).replace(/\.[^/.]+$/,""))`

This regex removes the extension of the main file before compilation, so:
`pdflatex example` instead of `pdflatex example.tex`.
This way, pdflatex defaults to search for files named `example` with the extension `.tex`. However, this removes the ability to compile non-`.tex`-files after all.

If I remove the `replace` command, it works just as intended for me. Is my deduction correct?
I created a pull request correcting this behaviour: https://github.com/James-Yu/Atom-LaTeX/pull/89

**Comment by James-Yu** [comment]
Thank you for the issue. As a PR has been made, I'd suggest we move to #89 for discussion.
