### ISSUE TITLE
Handeling external links and navigation in the PDF Viewer 

### ISSUE THREAD

**Issue by dpo** [James-Yu/Atom-LaTeX#87]
My PDF contains links to websites. If I click one of them, the PDF viewer window loads that page, but how do I navigate back and forth? The only way I found to come back to the PDF document is to recompile the LaTeX.

Thanks.

**Comment by ashthespy** [comment]
I don't think this use case has been considered so far.
However, there are two possible workarounds:
#### 1. Use the `PDF in new tab` mode 
With this, you can <kbd>ctrl</kbd>+<kbd>Mouse Click</kbd> to open up the links in a new browser window, thus leaving your PDF view intact.
#### 2. Use the `Preview PDF` menu toggle
Toggle the preview either via the toolbar button, or `Packages` → `Atom-LaTeX` → `Preview PDF`
This avoids an unnecessary recompile of the PDF, and rather just re opens the PDF.


I'm going to close this now, reopen if you face more trouble!

**Comment by exploide** [comment]
Ctrl+click still opens the website in an Atom / PDF preview window. Since such a window does not contain browser controls, I find it barely useful. Maybe it would be good to open web links in the external browser?!

**Comment by dpo** [comment]
Or just add forward and back buttons?! Standalone PDF viewers usually have them.

**Comment by exploide** [comment]
While I stumbled over this behavior again, a few minuted ago, I still prefer opening such links in the user's favorite full-featured browser.

**Comment by ashthespy** [comment]
I agree - it would be best if links are opened externally. I will look into it, in the meantime, the best alternative currently is to <kbd>ctrl</kbd>+<kbd>Mouse Click</kbd> on a link to have it open in a new Atom browser window.

**Comment by exploide** [comment]
Intuitively I would not assume that I can visit the links within the PDF viewer at all. So I would always expect that it opens in the external browser.

**Comment by dpo** [comment]
I agree but I presume the PDF viewer in this case is in fact a full-fledged browser window.

**Comment by ashthespy** [comment]
Sure, but should a normal click open up an external browser?
If I recall correctly, most PDF viewers (e.g Evince, Adobe Reader) need a special toggle (<kbd>ctrl</kbd> + <kbd>click</kbd>)  to open external links.

**Comment by exploide** [comment]
Maybe this is to avoid interfering with other PDF viewer features like text selection and further stuff like annotations (also often opened by a click). If there is no interference and one can use text selection and the features supported by this PDF viewer, single click to open browser should be fine.
