### ISSUE TITLE
Add a clear command

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#9]
LaTeX build processes typically create a lot of intermediate / auxiliary files. It would be nice if the package provides a clean command which deletes files like .aux, .log, .out, ... (maybe customizable).

**Comment by James-Yu** [comment]
I agree this is a useful feature and will work on it.

**Comment by James-Yu** [comment]
The feature is added in v`0.6.0`. Please check if it works as suggested.

**Comment by exploide** [comment]
Cool 👍 works as expected :)

I'm only wondering why .synctex.gz is the only one not removed. If you have reasons not adding this, I can at least add it manually in the preferences.

**Comment by James-Yu** [comment]
Because this file is needed for synctex to work. If the file is removed, neither direct nor reverse synctex can find their positions.

**Comment by exploide** [comment]
Ok, personally I see synctex as a tool used during active work and not as something useful to be preserved. But in the light of the clean-after-build option, your default behavior is understandable.

I tried to add synctex.gz to the clean-files list in my preferences but it does not work (guess the period is the reason). Would you mind allowing specifying extensions like abc.xyz? I would prefer this because gz is rather unspecific and matches to all gzipped files.

**Comment by James-Yu** [comment]
Yes that would be useful.

**Comment by James-Yu** [comment]
As you wish. Git checkout for the latest changes. Next update will be in days.
