### ISSUE TITLE
Syntax highlighting fails on long lines

### ISSUE THREAD

**Issue by exploide** [James-Yu/Atom-LaTeX#93]
I noticed that in some cases, syntax highlighting stops working, apparently on long lines. See screenshot below, where math mode and bold face in the last line are not highlighted anymore.

![bildschirmfoto vom 2017-08-03 19-27-19](https://user-images.githubusercontent.com/5670236/28934631-f60e0fcc-7881-11e7-92d3-af4967fc6502.png)

**Comment by ashthespy** [comment]
This is a current limitation of Atom, it matches only the first 100 tokens in a line.
I had a look at it in #74, and an option was the package [grammar-token-limit ]( https://atom.io/packages/grammar-token-limit), but the packages warns about a performance hit.

That being said, LaTeX should ignore line breaks, so in this case, you could just split your line where it's convenient.
