### ISSUE TITLE
Feature request: do not apply soft wrapping of lines within the 'table' environment

### ISSUE THREAD

**Issue by yhtang** [James-Yu/Atom-LaTeX#96]
Hi,

First thanks for creating this useful package for TeX editing!

I am wondering if it is possible to add an option to not apply soft wrapping within the table/tabular environment. The rationale is that some table source code are specifically aligned columnwise, and soft wrapping destroyes this alignment and reduces readability.

Thanks very much!

**Comment by ashthespy** [comment]
AFAIK, I don't it's possible to mix soft wraps within an editor - but I could be wrong!
I did try to switch it off by adding:
```
'.meta.function.environment.tabular.latex':
  'editor':
    'softWrap':false
```
to the [`language-latex.cson`](https://github.com/James-Yu/Atom-LaTeX/blob/master/settings/language-latex.cson) 
While atom reports the scope setting is indeed false, Doesn't really work!
![image](https://user-images.githubusercontent.com/16233271/29169994-f0ec4996-7dd6-11e7-8630-8a0edee90ac6.png)

**Comment by ashthespy** [comment]
Nope,  The  was soft warp is implemented in Atom is editor specific, and can't be changed within a scope in that editor. So unfortunately, this can't be implemented currently.

But when you think about it, it is a **soft** wrap in the end, so it will not alter your LaTeX source in anyway. I do agree it reduces readability though. 

You can still disable it for all LaTeX grammar by setting `softWrap: false`  in [`language-latex.cson`](https://github.com/James-Yu/Atom-LaTeX/blob/master/settings/language-latex.cson).
