### ISSUE TITLE
spawn latexmk/pdflatex ENOENT

### ISSUE THREAD

**Issue by Leithian** [James-Yu/Atom-LaTeX#99]
Great Package, but since a few days it's randomly starting to spit out "Failed building LaTeX (code ENOENT)" with the error Message "spawn latexmk/pdflatex ENOENT" (depending if I try to use the custom or latexmk toolchain). I'm on Windows 10 trying to use it with Atom 18-20 and TeXLive or MikTeX, I tried editing the path-variable, editing the config file, uninstalling and reinstalling the package, atom and LaTeX, and I still can't find a clue to what is causing this. On one PC I couldn't get it to start at all, on my laptop (both same configurations) it just happened again after a simple restart. Sometimes it started working again on my laptop, but after different things (one time reinstalling the package helped, another I had to reinstall atom, now nothing is working...).
Did this happen to anyone else or any ideas what could have caused this?

**Comment by ashthespy** [comment]
The `ENOENT` error should indicate that the package couldn't find the executable.

Could you provide a few more details/example of how you arrive at this issue?
1. Toolchain used (full `toolchain` with all arguments)
2. Are you able to run your `toolchain` command from a command prompt started from the directory of the main file?

**Comment by Leithian** [comment]
I wanted to use the standard custom toolchain with pdflatex and biber, but also tried the latexmk toolchain and auto. Arguments are `-synctex=1 -interaction=nonstopmode -file-line-error -pdf`. CMD execution and TeXStudio works....

**Comment by ashthespy** [comment]
Interesting!
Just to confirm:
You can run `pdflatex -synctex=1 -interaction=nonstopmode -file-line-error -pdf main.tex` fine from the command prompt, but it building the package throws up the `ENOENT` error?

Since I can't really reproduce the error - I am guessing it's to do the the environment variables - would you be willing to do a bit of digging/debugging?
1. Open the developer  console(<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd>) 
2. Run `process.env.Path.split(';')` and check if the correct path entries for `pdflatex`is there?  For MikTeX I believe it's `C:\Program Files\MiKTeX 2.9\miktex\bin\x64\`

**Comment by Leithian** [comment]
Yes, CMD is working (and TeXStudio), but the package throws the `ENOENT`. 
The `process.env.Path.split(';')` gives me the correct `C:\texlive\2016\bin\win32`. I'm trying to use TeXLive 2017 but in the 2016 folder as I updated, but I also tried it in the 2017 folder and MikTeX, although I uninstalled them afterwards. There is no other LaTeX installed right now and nothing in the Path.
Sorry for the trouble and thanks for your help.

**Comment by ashthespy** [comment]
Can you try setting `LaTeX Compiler to use` setting to the full path of the executable?
i.e `C:/texlive/2016/bin/win32/pdflatex` (Take note of the path deliminator :-)) and check if you still get the `ENOENT` error?

**Comment by Leithian** [comment]
Yes, now the error message just says "spawn C:/texlive/2016/bin/win32/pdflatex ENOENT". And I checked, there is a pdflatex.exe in that path.

**Comment by ashthespy** [comment]
I am starting to run out of ideas! :-( 
Last few though:
1. Can you try running `where pdflatex` from the cmd prompt? 
It should return in your case `C:\texlive\2016\bin\win32`
2. From the atom developer console, what is the output of `atom_latex.latex.builder.binCheck('pdflatex')`
if it's `true` could you proceed then try - 
3. Again from the dev console, does this return the expected `pdflatex` version information? 
`Tspawn = require('child_process').spawn('pdflatex', ['--version']);  Tspawn.stdout.on('data',function(data) {   console.log('OUTPUT: ' + data);});`
3. Now with the full path:
`Tspawn = require('child_process').spawn('C:/texlive/2016/bin/win32/pdflatex', ['--version']);  Tspawn.stdout.on('data',function(data) {   console.log('OUTPUT: ' + data);});`

If that still gives you the `Uncaught Error: spawn pdflatex ENOENT` then, this requires more digging. :-(

**Comment by Leithian** [comment]
1. It returns `C:\texlive\2016\bin\win32\pdflatex.exe`
2. It returns `true`
3&4: I'm getting a correct output, the version is the same as if I try `pdflatex --version` in CMD.

**Comment by Leithian** [comment]
I'm so sorry, it turns out the root file somehow was wrong, one of the magic comments had a typo and the compiler went with it. I got so confused by the error that I ignored the obvious.
Thanks for your help, I'm stunned by how stupid I was.

**Comment by ashthespy** [comment]
Ahha! I am glad that you caught it!
However, that should not throw this `ENOENT` error? 

The package would through it much earlier while trying to find dependent files.  
Would you mind (to satisfy my curiosity) what kind of document structure you were trying to compile that lead to this error?

**Comment by Leithian** [comment]
I'm using a quite complicated. I have a main folder for the project, and in this folder are several subfolders (sometimes with subfolders themselves) where all files are stored. My magic comments therefore look mostly like this: `%!TEX root = ../../LaTeX_Files/master.tex`.

**Comment by ashthespy** [comment]
On further though, I'd imagine due to the wrong path to  `master.tex` it would have messed up the `cwd` which then is what `spawn()` was throwing up `ENOENT` errors in your case, and not the `pdflatex` path.

Sorry that you had to waste time on this, I will look into if we can implement some sort of checks for such cases.

**Comment by Leithian** [comment]
Thanks for your help, I'm sorry I've bothered you with this typo
